In [1]:
import gcamreader
import pandas as pd
import os
from pathlib import Path
from pathlib import Path
import xml.etree.ElementTree as ET
from xml.dom import minidom

In [2]:
# =========================================================
# Config
# =========================================================
PROJECT_PATH   = Path("../")
DB_REL_PATH    = PROJECT_PATH / "output"
DB_FILE        = "database_basexdb_ERT"
QUERY_FILE     = DB_REL_PATH / "queries" / "Main_queries.xml"

REGION = ['South Korea']

In [3]:
# =========================================================
# DB helpers
# =========================================================
def connect_db():
    return gcamreader.LocalDBConn(DB_REL_PATH, DB_FILE)

def check_query_idx():
    queries = gcamreader.parse_batch_query(os.fspath(QUERY_FILE))
    for i, q in enumerate(queries):
        print(i, q.title)

def run_query(conn, q_idx, scenarios, regions=None):
    queries = gcamreader.parse_batch_query(os.fspath(QUERY_FILE))
    q = queries[q_idx]
    print(q.title)
    df = conn.runQuery(q, scenarios=scenarios, regions=regions)
    df["scenario"] = df["scenario"].str.split(",").str[0]
    return df

def get_scenario_name(conn):
    scenarios = list(conn.listScenariosInDB()['name'].unique())
    return scenarios

In [4]:
check_query_idx()

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 other industry production by region
145 other industry inputs by tech (energy and feedstocks)
146 other industry prices
147 energy-for-water TFE
148 energy-for-water FE by fuel
149 energy-for-water FE by process and fuel
150 prices of energy-for-water processes
151 water flow volumes of EFW processes
152 nonrenewable groundwater pumping energy
153 transport total final energy by region
154 transport total final energy by service
155 transport final energy by fuel
156 transport final energy by mode and fuel
157 transport final energy by tech and fuel
158 transport final energy by tech and vintage
159 transport final energy by tech (new)
160 transport service output by service
161 transport service output by mode
162 transport service output by tech
163 transport service output by tech and vintage
164 transport service output by tech (new)
165 transport load factors
166 fuel prices to transport
167 costs of transport services
168 costs of transport modes
169 costs of transport techs
170 transport tech non-energy cost
171 LDV energy by primary fuel
172 transport subsector share-weights
173 transport tech share-weights
174 transport speeds
175 building final energy by tech
176 building service output by tech
177 building floorspace
178 industry final energy by service and fuel
179 transport final energy by tech and fuel
180 transport final energy by tech (new)
181 transport service output by tech
182 transport service output by tech (new)
183 detailed land allocation
184 detailed historical land allocation
185 land allocation by crop
186 aggregated land allocation
187 aggregated historical land allocation
188 land allocation in a specified land use region
189 land allocation by crop and water source
190 LUC emissions by region
191 LUC emissions by LUT
192 LUC emissions by LUT in a specified land use region
193 vegetative carbon stock by region
194 profit rate
195 profit rate in a specified land use region
196 land leaf shares
197 land leaf shares in a specified land use region
198 ag production by crop type
199 ag production by subsector (land use region)
200 ag production in a specified land use region
201 ag production by tech
202 ag tech variable cost
203 ag tech yield
204 ag tech yield in a specified land region
205 ag commodity prices
206 ag tech implied subsidy
207 irrigation water withdrawals by region
208 irrigation water withdrawals by crop type
209 irrigation water withdrawals by crop type and land region
210 irrigation water withdrawals by ag tech
211 irrigation water consumption by region
212 irrigation water consumption by crop type
213 irrigation water consumption by crop type and land region
214 irrigation water consumption by ag tech
215 biophysical water demand by region
216 biophysical water demand by crop type
217 biophysical water demand by crop type and land region
218 biophysical water demand by ag tech
219 fertilizer consumption by region
220 fertilizer consumption by crop type
221 fertilizer consumption by ag tech
222 fertilizer-crop input-output coefficients
223 purpose-grown biomass production
224 residue biomass production
225 MSW production
226 regional biomass consumption
227 meat and dairy production by type
228 meat and dairy production by tech
229 meat and dairy prices
230 meat and dairy subsector share-weights
231 meat and dairy tech share-weights
232 meat and dairy subsector costs
233 meat and dairy tech costs
234 water consumption by meat and dairy production
235 feed consumption by region
236 feed consumption by meat and dairy tech
237 feed sources
238 feed prices
239 feed subsector share-weights
240 food consumption by type (general)
241 food consumption by type (specific)
242 demand balances by crop commodity
243 demand balances by meat and dairy commodity
244 food demand prices
245 food demand
246 food demand per capita
247 food demand regional bias
248 ag import vs. domestic supply (Regional Armington competition)
249 ag export to the world center (USA) (Intl. Armington competition)
250 ag import vs. domestic prices
251 ag export prices (at world center USA)
252 import vs. domestic share-weights (Armington regional taste)
253 international competition share-weights (Armington intl. taste)
254 ag total prices (weighted average b/t domestic and imported prices)
255 opening stocks (supply from carryover)
256 closing stocks (before loss/adjustments)
257 closing stocks (after loss/adjustments; carried over)
258 current supply (current or regional consumption)
259 ag regional prices (current consumer prices)
260 agricultural storage share-weights
261 storage cost
262 expected price
263 CO2 emissions by region
264 CO2 emissions by sector (excluding resource production)
265 CO2 emissions by sector (no bio) (excluding resource production)
266 CO2 emissions by assigned sector (no bio) (excluding resource production)
267 CO2 emissions by subsector (excluding resource production)
268 CO2 emissions by tech (excluding resource production)
269 CO2 emissions by resource production
270 CO2 sequestration by sector
271 CO2 sequestration by tech
272 nonCO2 emissions by region
273 nonCO2 emissions by sector (excluding resource production)
274 nonCO2 emissions by resource production
275 nonCO2 emissions by subsector (excluding resource production)
276 nonCO2 emissions by tech (excluding resource production)
277 specific nonCO2 emissions by region
278 specific nonCO2 emissions by sector (excluding resource production)
279 specific nonCO2 emissions by resource production
280 specific nonCO2 emissions by subsector (excluding resource production)
281 specific nonCO2 emissions by tech (excluding resource production)
282 CO2 concentrations
283 total climate forcing
284 global mean temperature
285 net terrestrial C uptake
286 population by region
287 GDP MER by region
288 GDP per capita MER by region
289 GDP per capita PPP by region
290 subregional population
291 subregional income
292 National Account
293 Social Accounting Matrix
294 Tracking accounts by tech
295 Capital investment demands by tech
296 Capital investment demands by resource
297 CO2 prices
298 policy cost by period
299 undiscounted policy cost
300 discounted policy cost
301 regional CO2 MAC curves by period
302 water withdrawals by region
303 water withdrawals by water mapping source
304 water withdrawals by sector
305 water withdrawals by subsector
306 water withdrawals by tech
307 water consumption by region
308 water consumption by water mapping source
309 water consumption by sector
310 water consumption by subsector
311 water consumption by tech
312 Basin level available runoff
313 Water withdrawals by water source (runoff vs. groundwater)
314 Water Withdrawals by Basin (Runoff)
315 Water Withdrawals by Basin (Groundwater)
316 Cumulative groundwater extraction
317 prices of all markets
318 supply of all markets
319 demand of all markets
320 price of a specific market
321 supply of a specific market
322 prices by sector
323 costs by subsector
324 costs by tech
325 costs by tech and input
326 inputs by sector
327 inputs by subsector
328 inputs by tech
329 outputs by sector
330 outputs by subsector
331 outputs by tech
332 input-output coefficients by tech
333 primary energy consumption by region (direct equivalent)
334 industry water withdrawals and consumption
335 elec gen by region (no CHP)
336 elec gen by subsector
337 elec gen by gen tech (cogen only)
338 elec gen by gen tech and cooling tech (incl cogen)
339 elec energy input by subsector
340 elec energy input by elec gen tech
341 elec prices by sector
342 elec gen costs by subsector
343 elec gen costs by tech
344 elec share-weights by subsector
345 elec share-weights by gen tech
346 elec share-weights by cooling tech
347 elec water withdrawals by gen tech and cooling tech
348 elec water consumption by gen tech and cooling tech
349 refined liquids production by region
350 refined liquids production by subsector
351 refined liquids production by tech
352 refined liquids production by tech and vintage
353 refined liquids production by tech (new)
354 refinery inputs by tech (energy and feedstocks)
355 refined liquids prices by sector
356 refined liquids costs by subsector
357 refined liquids costs by tech
358 refining and oil share-weights by subsector
359 refining share-weights by tech
360 total final energy by aggregate sector
361 water withdrawals by state, sector, basin
362 water withdrawals by state, sector, basin (includes desal)
363 water consumption by state, sector, basin
364 water consumption by state, sector, basin (includes desal)
365 CO2 emissions by tech (nested subsector) (excluding resource production)
366 CO2 sequestration by tech (nested subsector)

In [5]:
conn = connect_db()
get_scenario_name(conn)

Database scenarios: Baseline, Competitiveness-Erosion, Trade-Regulation, Twin-Burden, Twin-Burden-RD

['Baseline',
 'Competitiveness-Erosion',
 'Trade-Regulation',
 'Twin-Burden',
 'Twin-Burden-RD']

In [6]:
scenarios = ['Baseline', 'Competitiveness-Erosion']

In [7]:
dfCO2 = run_query(conn=conn, q_idx=265, scenarios=scenarios, regions=REGION)
dfCO2

CO2 emissions by sector (no bio) (excluding resource production)

,Units,scenario,region,sector,Year,value
0,MTC,Baseline,South Korea,H2 central production,2025,3.074355e-03
1,MTC,Baseline,South Korea,H2 central production,2030,8.137879e-02
2,MTC,Baseline,South Korea,H2 central production,2035,1.931381e-01
3,MTC,Baseline,South Korea,H2 central production,2040,3.048566e-01
4,MTC,Baseline,South Korea,H2 central production,2045,3.138861e-01
...,...,...,...,...,...,...
1685,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,2045,-1.226540e-02
1686,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,2050,-1.586002e-02
1687,MTC,Competitiveness-Erosion,South Korea,wholesale gas,2010,-8.331578e-08
1688,MTC,Competitiveness-Erosion,South Korea,wholesale gas,2015,-1.856498e-07
1689,MTC,Competitiveness-Erosion,South Korea,wholesale gas,2030,-1.764739e-07

In [8]:
dfCO2Price = run_query(conn=conn, q_idx=297, scenarios=scenarios)
dfCO2Price

CO2 prices

        Units                 scenario  Year          market  value
0    1990$/tC                 Baseline  1975        EU-27CO2    0.0
1    1990$/tC                 Baseline  1975          RoWCO2    0.0
2    1990$/tC                 Baseline  1975  South KoreaCO2    0.0
3    1990$/tC                 Baseline  1990        EU-27CO2    0.0
4    1990$/tC                 Baseline  1990          RoWCO2    0.0
..        ...                      ...   ...             ...    ...
127  1990$/tC  Competitiveness-Erosion  2095          RoWCO2    0.0
128  1990$/tC  Competitiveness-Erosion  2095  South KoreaCO2    0.0
129  1990$/tC  Competitiveness-Erosion  2100        EU-27CO2    0.0
130  1990$/tC  Competitiveness-Erosion  2100          RoWCO2    0.0
131  1990$/tC  Competitiveness-Erosion  2100  South KoreaCO2    0.0

[132 rows x 5 columns]

In [9]:
CONVERT_FROM_1990_TO_2005 = 117.53 / 66.168
CONVERT_FROM_TC_TO_TCO2 = 12 / 44

In [10]:
dfCO2Price[(dfCO2Price['Year'] >= 2025) & (dfCO2Price['Year'] <= 2050)].pivot(index='Year', columns=['scenario', 'market'], values='value')

scenario Baseline                         Competitiveness-Erosion           \
market   EU-27CO2   RoWCO2 South KoreaCO2                EU-27CO2   RoWCO2
Year
2025      251.751    0.000        187.719                 251.751    0.000
2030      335.600  157.332        237.785                 335.595  157.288
2035      392.638  230.900        269.823                 392.603  230.828
2040      422.143  281.404        308.457                 422.098  281.307
2045      414.450  328.877        342.462                 414.276  328.751
2050      398.927  379.541        365.956                 398.425  379.057

scenario
market   South KoreaCO2
Year
2025            187.719
2030            220.834
2035            237.444
2040            260.696
2045            297.039
2050            353.486

In [11]:
dfCO2Price['value'] *= (CONVERT_FROM_1990_TO_2005 * CONVERT_FROM_TC_TO_TCO2)

In [12]:
dfCO2Price[(dfCO2Price['Year'] >= 2025) & (dfCO2Price['Year'] <= 2050)].pivot(index='Year', columns=['scenario', 'market'], values='value')

scenario    Baseline                            Competitiveness-Erosion  \
market      EU-27CO2      RoWCO2 South KoreaCO2                EU-27CO2
Year
2025      121.955250    0.000000      90.936352              121.955250
2030      162.574059   76.216037     115.189728              162.571637
2035      190.204868  111.854441     130.709834              190.187913
2040      204.497918  136.319996     149.425228              204.476118
2045      200.771213  159.317250     165.898205              200.686922
2050      193.251436  183.860313     177.279358              193.008253

scenario
market        RoWCO2 South KoreaCO2
Year
2025        0.000000      90.936352
2030       76.194722     106.978188
2035      111.819562     115.024538
2040      136.273006     126.288459
2045      159.256212     143.894029
2050      183.625850     171.238540

In [13]:
dfCO2Price['Units'] = "2020$/tCO2"
dfCO2Price['pathway'] = 'ERT'
dfCO2Price[(dfCO2Price['Year'] >= 2025) & (dfCO2Price['Year'] <= 2050)].to_csv("./output/ERT_carbon_tax.csv", index=False)

In [14]:
dfSteelPrice = run_query(conn=conn, q_idx=122, scenarios=scenarios, regions=REGION)
dfSteelPrice[(dfSteelPrice['Year'] >= 2025) & (dfSteelPrice['Year'] <= 2050)].pivot(index='Year', columns='scenario', values='value')

iron and steel prices

scenario  Baseline  Competitiveness-Erosion
Year
2025      0.238424                 0.238424
2030      0.241132                 0.238890
2035      0.243425                 0.239749
2040      0.247102                 0.242592
2045      0.249937                 0.246300
2050      0.251985                 0.250547

In [15]:
us_export_share = 0.13
dfTariff = dfSteelPrice[(dfSteelPrice['Year'] >= 2025) & (dfSteelPrice['Year'] <= 2050)].pivot(index='Year', columns='scenario', values='value').copy()
dfTariff['tariff rate'] = [0, 0.5, 0.5, 0, 0, 0]
dfTariff['tariff-Baseline'] = dfTariff['Baseline'] * dfTariff['tariff rate'] * us_export_share
dfTariff['tariff-Competitiveness-Erosion'] = dfTariff['Competitiveness-Erosion'] * dfTariff['tariff rate'] * us_export_share
dfTariff

scenario,Baseline,Competitiveness-Erosion,tariff rate,tariff-Baseline,tariff-Competitiveness-Erosion
Year,,,,,
2025,0.238424,0.238424,0.0,0.000000,0.000000
2030,0.241132,0.238890,0.5,0.015674,0.015528
2035,0.243425,0.239749,0.5,0.015823,0.015584
2040,0.247102,0.242592,0.0,0.000000,0.000000
2045,0.249937,0.246300,0.0,0.000000,0.000000
2050,0.251985,0.250547,0.0,0.000000,0.000000

In [16]:
dfUsTariff = dfTariff.stack().reset_index().copy()
dfUsTariff = dfUsTariff[(dfUsTariff['Year'].isin([2030, 2035]))].copy()
dfUsTariff['pathway'] = 'ERT'
dfUsTariff.rename(columns={0: '1975$/kg'}).to_csv("./output/ERT_us_tariff.csv", index=False)

In [17]:
def build_tariff_xml(
    df,
    tariff_col="tariff-Baseline",
    region="USA",
    supplysector="traded iron and steel",
    subsector="South Korea traded iron and steel",
    technology="South Korea traded iron and steel"
):

    scenario = ET.Element("scenario")
    world = ET.SubElement(scenario, "world")
    region_el = ET.SubElement(world, "region", name=region)
    ss = ET.SubElement(region_el, "supplysector", name=supplysector)
    subsector_el = ET.SubElement(ss, "subsector", name=subsector)
    tech = ET.SubElement(subsector_el, "technology", name=technology)

    for year, row in df.iterrows():
        period = ET.SubElement(tech, "period", year=str(year))
        nie = ET.SubElement(period, "minicam-non-energy-input", name="tariff")
        cost = ET.SubElement(nie, "input-cost")
        cost.text = f"{row[tariff_col]:.4f}"

    return ET.ElementTree(scenario)

In [18]:
tree = build_tariff_xml(dfTariff, tariff_col="tariff-Baseline")
ET.indent(tree, space="    ")   # ⭐ 이 줄 하나가 핵심
tree.write(
    f"../input/policy/industry/ironsteel_tariff_ERT_Baseline.xml",
    encoding="UTF-8",
    xml_declaration=True
)

# Baseline

In [19]:
dfTax = run_query(conn=conn, q_idx=297, scenarios=['Baseline'])
dfTax = dfTax[(dfTax['Year'] <= 2050) & (dfTax['Year'] >= 2021) & (dfTax['market'].isin(['EU-27CO2', 'South KoreaCO2']))].pivot(index='Year', columns='market', values='value').copy()
dfTax['St_EU'] = [0, 0, 0.485, 1, 1, 1, 1]
dfTax['St_KOR'] = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
dfTax['P_EU_eff'] = dfTax['St_EU'] * dfTax['EU-27CO2']
dfTax['P_KOR_eff'] = dfTax['St_KOR'] * dfTax['South KoreaCO2']
dfTax['D'] = (dfTax['P_EU_eff'] - dfTax['P_KOR_eff'])
dfTax

CO2 prices

market  EU-27CO2  South KoreaCO2  St_EU  St_KOR  P_EU_eff  P_KOR_eff         D
Year
2021       0.000           0.000  0.000     0.0     0.000     0.0000    0.0000
2025     251.751         187.719  0.000     0.1     0.000    18.7719  -18.7719
2030     335.600         237.785  0.485     0.2   162.766    47.5570  115.2090
2035     392.638         269.823  1.000     0.3   392.638    80.9469  311.6911
2040     422.143         308.457  1.000     0.4   422.143   123.3828  298.7602
2045     414.450         342.462  1.000     0.5   414.450   171.2310  243.2190
2050     398.927         365.956  1.000     0.6   398.927   219.5736  179.3534

In [20]:
dfCO2 = run_query(conn=conn, q_idx=268, scenarios=['Baseline'], regions=['South Korea'])
dfCO2

CO2 emissions by tech (excluding resource production)

,Units,scenario,region,sector,subsector,technology,Year,value
0,MTC,Baseline,South Korea,H2 central production,biomass,biomass to H2,2025,0.001075
1,MTC,Baseline,South Korea,H2 central production,biomass,biomass to H2,2030,0.032934
2,MTC,Baseline,South Korea,H2 central production,biomass,biomass to H2,2035,0.083659
3,MTC,Baseline,South Korea,H2 central production,biomass,biomass to H2,2040,0.147018
4,MTC,Baseline,South Korea,H2 central production,biomass,biomass to H2,2045,0.163364
...,...,...,...,...,...,...,...,...
1990,MTC,Baseline,South Korea,waste biomass for paper,biomass,biomass cogen,2030,0.153721
1991,MTC,Baseline,South Korea,waste biomass for paper,biomass,biomass cogen,2035,0.156263
1992,MTC,Baseline,South Korea,waste biomass for paper,biomass,biomass cogen,2040,0.164428
1993,MTC,Baseline,South Korea,waste biomass for paper,biomass,biomass cogen,2045,0.172183
1994,MTC,Baseline,South Korea,waste biomass for paper,biomass,biomass cogen,2050,0.169911

In [21]:
arrCO2SteelDirect = dfCO2[(dfCO2['sector'].str.contains('iron and steel')) & (dfCO2['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrCO2SteelDirect

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  17.989140
                                                BLASTFUR CCS               0.061916
                                                BLASTFUR with hydrogen     0.146227
                                                Biomass-based              0.590750
                                EAF with DRI    EAF with DRI               0.600887
                                                EAF with DRI CCS           0.006843
                                EAF with scrap  EAF with scrap             0.791416
          2035  iron and steel  BLASTFUR        BLASTFUR                  14.364250
                                                BLASTFUR CCS               0.251336
                                                BLASTFUR with hydrogen     0.378164
                                                Biomass-based              1.610240
                                EAF with DRI    EAF with DRI               1.037067
                                                EAF with DRI CCS           0.037575
                                EAF with scrap  EAF with scrap             0.994263
          2040  iron and steel  BLASTFUR        BLASTFUR                  10.405133
                                                BLASTFUR CCS               0.457573
                                                BLASTFUR with hydrogen     0.521445
                                                Biomass-based              2.347426
                                EAF with DRI    EAF with DRI               1.277467
                                                EAF with DRI CCS           0.082844
                                EAF with scrap  EAF with scrap             1.115528
          2045  iron and steel  BLASTFUR        BLASTFUR                   8.944544
                                                BLASTFUR CCS               0.591223
                                                BLASTFUR with hydrogen     0.539778
                                                Biomass-based              2.558226
                                EAF with DRI    EAF with DRI               1.285810
                                                EAF with DRI CCS           0.127340
                                EAF with scrap  EAF with scrap             1.161929
          2050  iron and steel  BLASTFUR        BLASTFUR                   7.322572
                                                BLASTFUR CCS               0.738576
                                                BLASTFUR with hydrogen     0.541929
                                                Biomass-based              2.545210
                                EAF with DRI    EAF with DRI               1.267253
                                                EAF with DRI CCS           0.194060
                                EAF with scrap  EAF with scrap             1.204198
Name: value, dtype: float64

In [22]:
dfElec = run_query(conn=conn, q_idx=8, scenarios=['Baseline'], regions=['South Korea'])
dfElec.groupby('Year')['value'].sum()

elec gen by subsector

Year
1990    0.358142
2005    1.313811
2010    1.696271
2015    1.879333
2021    2.076581
2025    2.199723
2030    2.383019
2035    2.598362
2040    2.836362
2045    3.051413
2050    3.155784
Name: value, dtype: float64

In [23]:
dfCO2[(dfCO2['sector'].str.contains('elec'))].groupby('Year')['value'].sum()

Year
1990     9.396560
2005    47.407164
2010    67.239118
2015    69.733274
2021    68.565066
2025    55.276003
2030    41.423475
2035    30.679653
2040    23.948543
2045    18.593319
2050    13.524348
Name: value, dtype: float64

In [24]:
arrElecI = dfCO2[(dfCO2['Year'] >= 2030) & (dfCO2['sector'].str.contains('elec'))].groupby('Year')['value'].sum() / dfElec[(dfElec['Year'] >= 2030)].groupby('Year')['value'].sum()
arrElecI

Year
2030    17.382774
2035    11.807305
2040     8.443401
2045     6.093347
2050     4.285575
Name: value, dtype: float64

In [25]:
dfH2 = run_query(conn=conn, q_idx=45, scenarios=['Baseline'], regions=['South Korea'])
dfH2.groupby('Year')['value'].sum()

hydrogen production by tech

Year
2025    0.000249
2030    0.011733
2035    0.040830
2040    0.095236
2045    0.134524
2050    0.165882
Name: value, dtype: float64

In [26]:
dfCO2[(dfCO2['sector'].str.contains('H2'))].groupby('Year')['value'].sum()

Year
2025    0.004918
2030    0.196553
2035    0.621879
2040    1.344441
2045    1.819833
2050    2.119261
Name: value, dtype: float64

In [27]:
arrH2I = dfCO2[(dfCO2['Year'] >= 2030) & (dfCO2['sector'].str.contains('H2'))].groupby('Year')['value'].sum() / dfH2[(dfH2['Year'] >= 2030)].groupby('Year')['value'].sum()
arrH2I

Year
2030    16.752412
2035    15.231101
2040    14.116967
2045    13.527964
2050    12.775682
Name: value, dtype: float64

In [28]:
dfElecI = arrElecI.reset_index()
dfElecI['input'] = 'elect_td_ind'
dfElecI

   Year      value         input
0  2030  17.382774  elect_td_ind
1  2035  11.807305  elect_td_ind
2  2040   8.443401  elect_td_ind
3  2045   6.093347  elect_td_ind
4  2050   4.285575  elect_td_ind

In [29]:
dfH2I = arrH2I.reset_index()
dfH2I['input'] = 'H2 industrial'
dfH2I

   Year      value          input
0  2030  16.752412  H2 industrial
1  2035  15.231101  H2 industrial
2  2040  14.116967  H2 industrial
3  2045  13.527964  H2 industrial
4  2050  12.775682  H2 industrial

In [30]:
df_ci = pd.concat([dfElecI, dfH2I], axis=0).rename(columns={'value': 'ci'})
df_ci

   Year         ci          input
0  2030  17.382774   elect_td_ind
1  2035  11.807305   elect_td_ind
2  2040   8.443401   elect_td_ind
3  2045   6.093347   elect_td_ind
4  2050   4.285575   elect_td_ind
0  2030  16.752412  H2 industrial
1  2035  15.231101  H2 industrial
2  2040  14.116967  H2 industrial
3  2045  13.527964  H2 industrial
4  2050  12.775682  H2 industrial

In [31]:
dfInput = run_query(conn=conn, q_idx=100, scenarios=['Baseline'], regions=['South Korea'])
dfInputIndirect = dfInput[(dfInput['sector'] == 'iron and steel') & (dfInput['input'].isin(['elect_td_ind', 'H2 industrial'])) & (dfInput['Year'] >= 2030)].copy()
df_indirect = (
    dfInputIndirect
    .merge(df_ci, on=["input", "Year"], how="left")
)
df_indirect["indirect_emissions_MtC"] = (
    df_indirect["value"] * df_indirect["ci"]
)
df_indirect
arrCO2SteelIndirect = df_indirect.groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['indirect_emissions_MtC'].sum()
arrCO2SteelIndirect

industry final energy by tech and fuel

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  1.007778
                                                BLASTFUR CCS              0.084092
                                                BLASTFUR with hydrogen    0.032310
                                                Biomass-based             0.038198
                                EAF with DRI    EAF with DRI              0.043795
                                                EAF with DRI CCS          0.004987
                                                Hydrogen-based DRI        0.018726
                                EAF with scrap  EAF with scrap            1.772010
          2035  iron and steel  BLASTFUR        BLASTFUR                  0.546600
                                                BLASTFUR CCS              0.231867
                                                BLASTFUR with hydrogen    0.069988
                                                Biomass-based             0.070722
                                EAF with DRI    EAF with DRI              0.051342
                                                EAF with DRI CCS          0.018602
                                                Hydrogen-based DRI        0.058666
                                EAF with scrap  EAF with scrap            1.512148
          2040  iron and steel  BLASTFUR        BLASTFUR                  0.283140
                                                BLASTFUR CCS              0.301865
                                                BLASTFUR with hydrogen    0.084287
                                                Biomass-based             0.073726
                                EAF with DRI    EAF with DRI              0.045226
                                                EAF with DRI CCS          0.029329
                                                Hydrogen-based DRI        0.097252
                                EAF with scrap  EAF with scrap            1.213223
          2045  iron and steel  BLASTFUR        BLASTFUR                  0.175651
                                                BLASTFUR CCS              0.281476
                                                BLASTFUR with hydrogen    0.079342
                                                Biomass-based             0.057984
                                EAF with DRI    EAF with DRI              0.032851
                                                EAF with DRI CCS          0.032534
                                                Hydrogen-based DRI        0.125857
                                EAF with scrap  EAF with scrap            0.911966
          2050  iron and steel  BLASTFUR        BLASTFUR                  0.101137
                                                BLASTFUR CCS              0.247309
                                                BLASTFUR with hydrogen    0.072078
                                                Biomass-based             0.040574
                                EAF with DRI    EAF with DRI              0.022771
                                                EAF with DRI CCS          0.034871
                                                Hydrogen-based DRI        0.167491
                                EAF with scrap  EAF with scrap            0.664736
Name: indirect_emissions_MtC, dtype: float64

In [32]:
arrCO2SteelDirect

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  17.989140
                                                BLASTFUR CCS               0.061916
                                                BLASTFUR with hydrogen     0.146227
                                                Biomass-based              0.590750
                                EAF with DRI    EAF with DRI               0.600887
                                                EAF with DRI CCS           0.006843
                                EAF with scrap  EAF with scrap             0.791416
          2035  iron and steel  BLASTFUR        BLASTFUR                  14.364250
                                                BLASTFUR CCS               0.251336
                                                BLASTFUR with hydrogen     0.378164
                                                Biomass-based              1.610240
                                EAF with DRI    EAF with DRI               1.037067
                                                EAF with DRI CCS           0.037575
                                EAF with scrap  EAF with scrap             0.994263
          2040  iron and steel  BLASTFUR        BLASTFUR                  10.405133
                                                BLASTFUR CCS               0.457573
                                                BLASTFUR with hydrogen     0.521445
                                                Biomass-based              2.347426
                                EAF with DRI    EAF with DRI               1.277467
                                                EAF with DRI CCS           0.082844
                                EAF with scrap  EAF with scrap             1.115528
          2045  iron and steel  BLASTFUR        BLASTFUR                   8.944544
                                                BLASTFUR CCS               0.591223
                                                BLASTFUR with hydrogen     0.539778
                                                Biomass-based              2.558226
                                EAF with DRI    EAF with DRI               1.285810
                                                EAF with DRI CCS           0.127340
                                EAF with scrap  EAF with scrap             1.161929
          2050  iron and steel  BLASTFUR        BLASTFUR                   7.322572
                                                BLASTFUR CCS               0.738576
                                                BLASTFUR with hydrogen     0.541929
                                                Biomass-based              2.545210
                                EAF with DRI    EAF with DRI               1.267253
                                                EAF with DRI CCS           0.194060
                                EAF with scrap  EAF with scrap             1.204198
Name: value, dtype: float64

In [33]:
arrCO2Steel = arrCO2SteelIndirect.add(arrCO2SteelDirect, fill_value=0)
arrCO2Steel

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  18.996918
                                                BLASTFUR CCS               0.146007
                                                BLASTFUR with hydrogen     0.178537
                                                Biomass-based              0.628948
                                EAF with DRI    EAF with DRI               0.644682
                                                EAF with DRI CCS           0.011830
                                                Hydrogen-based DRI         0.018726
                                EAF with scrap  EAF with scrap             2.563426
          2035  iron and steel  BLASTFUR        BLASTFUR                  14.910850
                                                BLASTFUR CCS               0.483204
                                                BLASTFUR with hydrogen     0.448152
                                                Biomass-based              1.680962
                                EAF with DRI    EAF with DRI               1.088409
                                                EAF with DRI CCS           0.056178
                                                Hydrogen-based DRI         0.058666
                                EAF with scrap  EAF with scrap             2.506411
          2040  iron and steel  BLASTFUR        BLASTFUR                  10.688273
                                                BLASTFUR CCS               0.759439
                                                BLASTFUR with hydrogen     0.605732
                                                Biomass-based              2.421152
                                EAF with DRI    EAF with DRI               1.322693
                                                EAF with DRI CCS           0.112173
                                                Hydrogen-based DRI         0.097252
                                EAF with scrap  EAF with scrap             2.328751
          2045  iron and steel  BLASTFUR        BLASTFUR                   9.120195
                                                BLASTFUR CCS               0.872699
                                                BLASTFUR with hydrogen     0.619120
                                                Biomass-based              2.616210
                                EAF with DRI    EAF with DRI               1.318661
                                                EAF with DRI CCS           0.159873
                                                Hydrogen-based DRI         0.125857
                                EAF with scrap  EAF with scrap             2.073895
          2050  iron and steel  BLASTFUR        BLASTFUR                   7.423709
                                                BLASTFUR CCS               0.985885
                                                BLASTFUR with hydrogen     0.614006
                                                Biomass-based              2.585784
                                EAF with DRI    EAF with DRI               1.290024
                                                EAF with DRI CCS           0.228931
                                                Hydrogen-based DRI         0.167491
                                EAF with scrap  EAF with scrap             1.868934
dtype: float64

In [34]:
dfSteelTech = run_query(conn=conn, q_idx=119, scenarios=['Baseline'], regions=['South Korea'])
arrSteelTech = dfSteelTech[(dfSteelTech['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrSteelTech

iron and steel production by tech

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  40.330930
                                                BLASTFUR CCS               1.738790
                                                BLASTFUR with hydrogen     0.402609
                                                Biomass-based              1.528650
                                EAF with DRI    EAF with DRI               0.730706
                                                EAF with DRI CCS           0.083210
                                                Hydrogen-based DRI         0.062998
                                EAF with scrap  EAF with scrap            25.125200
          2035  iron and steel  BLASTFUR        BLASTFUR                  32.204140
                                                BLASTFUR CCS               7.058320
                                                BLASTFUR with hydrogen     1.041204
                                                Biomass-based              4.166730
                                EAF with DRI    EAF with DRI               1.261119
                                                EAF with DRI CCS           0.456934
                                                Hydrogen-based DRI         0.228044
                                EAF with scrap  EAF with scrap            31.564990
          2040  iron and steel  BLASTFUR        BLASTFUR                  23.327873
                                                BLASTFUR CCS              12.850136
                                                BLASTFUR with hydrogen     1.435700
                                                Biomass-based              6.074305
                                EAF with DRI    EAF with DRI               1.553457
                                                EAF with DRI CCS           1.007425
                                                Hydrogen-based DRI         0.422264
                                EAF with scrap  EAF with scrap            35.414910
          2045  iron and steel  BLASTFUR        BLASTFUR                  20.053320
                                                BLASTFUR CCS              16.603426
                                                BLASTFUR with hydrogen     1.486176
                                                Biomass-based              6.619785
                                EAF with DRI    EAF with DRI               1.563602
                                                EAF with DRI CCS           1.548506
                                                Hydrogen-based DRI         0.587556
                                EAF with scrap  EAF with scrap            36.888020
          2050  iron and steel  BLASTFUR        BLASTFUR                  16.416910
                                                BLASTFUR CCS              20.741580
                                                BLASTFUR with hydrogen     1.492099
                                                Biomass-based              6.586100
                                EAF with DRI    EAF with DRI               1.541037
                                                EAF with DRI CCS           2.359870
                                                Hydrogen-based DRI         0.847993
                                EAF with scrap  EAF with scrap            38.229910
Name: value, dtype: float64

In [35]:
arrTax = dfTax[(dfTax.index >= 2030)]['D'] # 1990$ / tC
arrTax

Year
2030    115.2090
2035    311.6911
2040    298.7602
2045    243.2190
2050    179.3534
Name: D, dtype: float64

In [36]:
arrCO2I = (arrCO2Steel / arrSteelTech) # MtC / Mt = tC / t
arrCO2I

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  0.471026
                                                BLASTFUR CCS              0.083971
                                                BLASTFUR with hydrogen    0.443451
                                                Biomass-based             0.411440
                                EAF with DRI    EAF with DRI              0.882273
                                                EAF with DRI CCS          0.142170
                                                Hydrogen-based DRI        0.297253
                                EAF with scrap  EAF with scrap            0.102026
          2035  iron and steel  BLASTFUR        BLASTFUR                  0.463010
                                                BLASTFUR CCS              0.068459
                                                BLASTFUR with hydrogen    0.430418
                                                Biomass-based             0.403425
                                EAF with DRI    EAF with DRI              0.863050
                                                EAF with DRI CCS          0.122945
                                                Hydrogen-based DRI        0.257260
                                EAF with scrap  EAF with scrap            0.079405
          2040  iron and steel  BLASTFUR        BLASTFUR                  0.458176
                                                BLASTFUR CCS              0.059100
                                                BLASTFUR with hydrogen    0.421907
                                                Biomass-based             0.398589
                                EAF with DRI    EAF with DRI              0.851451
                                                EAF with DRI CCS          0.111347
                                                Hydrogen-based DRI        0.230311
                                EAF with scrap  EAF with scrap            0.065756
          2045  iron and steel  BLASTFUR        BLASTFUR                  0.454797
                                                BLASTFUR CCS              0.052561
                                                BLASTFUR with hydrogen    0.416586
                                                Biomass-based             0.395211
                                EAF with DRI    EAF with DRI              0.843348
                                                EAF with DRI CCS          0.103244
                                                Hydrogen-based DRI        0.214204
                                EAF with scrap  EAF with scrap            0.056221
          2050  iron and steel  BLASTFUR        BLASTFUR                  0.452199
                                                BLASTFUR CCS              0.047532
                                                BLASTFUR with hydrogen    0.411505
                                                Biomass-based             0.392612
                                EAF with DRI    EAF with DRI              0.837114
                                                EAF with DRI CCS          0.097010
                                                Hydrogen-based DRI        0.197515
                                EAF with scrap  EAF with scrap            0.048887
dtype: float64

In [37]:
dfCo2I = (arrCO2I * 44/12).reset_index()
dfCo2I = dfCo2I[(dfCo2I['Year'].isin([2035, 2050]))].pivot(index=['subsector', 'technology'], columns='Year', values=0).reset_index()
dfCo2I['unit'] = 'tCO2 / t'
dfCo2I['sector'] = 'iron and steel'
dfCo2I.to_csv("./output/ironsteel_carbon_intensity.csv", index=False)
dfCo2I

Year,subsector,technology,2035,2050,unit,sector
0,BLASTFUR,BLASTFUR,1.697705,1.658063,tCO2 / t,iron and steel
1,BLASTFUR,BLASTFUR CCS,0.251015,0.174283,tCO2 / t,iron and steel
2,BLASTFUR,BLASTFUR with hydrogen,1.578198,1.508852,tCO2 / t,iron and steel
3,BLASTFUR,Biomass-based,1.479224,1.439578,tCO2 / t,iron and steel
4,EAF with DRI,EAF with DRI,3.164516,3.069420,tCO2 / t,iron and steel
5,EAF with DRI,EAF with DRI CCS,0.450799,0.355704,tCO2 / t,iron and steel
6,EAF with DRI,Hydrogen-based DRI,0.943285,0.724222,tCO2 / t,iron and steel
7,EAF with scrap,EAF with scrap,0.291151,0.179251,tCO2 / t,iron and steel

In [38]:
ALPHA_EU_STEEL = (2.76/63.65) # 2024 Korea Iron and Steel Association (KOSA)
CONVERT_1990_TO_1975 = 31.01 / 66.16
arrUse = ALPHA_EU_STEEL * arrCO2I * arrTax * CONVERT_1990_TO_1975 / 1000 # (tC/t) * (1990$/tC) * (1975$/1990$) / (t/kg) = (1975$/kg)
arrUse

scenario  Year  sector          subsector       technology
Baseline  2030  iron and steel  BLASTFUR        BLASTFUR                  0.001103
                                                BLASTFUR CCS              0.000197
                                                BLASTFUR with hydrogen    0.001038
                                                Biomass-based             0.000963
                                EAF with DRI    EAF with DRI              0.002066
                                                EAF with DRI CCS          0.000333
                                                Hydrogen-based DRI        0.000696
                                EAF with scrap  EAF with scrap            0.000239
          2035  iron and steel  BLASTFUR        BLASTFUR                  0.002933
                                                BLASTFUR CCS              0.000434
                                                BLASTFUR with hydrogen    0.002727
                                                Biomass-based             0.002556
                                EAF with DRI    EAF with DRI              0.005467
                                                EAF with DRI CCS          0.000779
                                                Hydrogen-based DRI        0.001630
                                EAF with scrap  EAF with scrap            0.000503
          2040  iron and steel  BLASTFUR        BLASTFUR                  0.002782
                                                BLASTFUR CCS              0.000359
                                                BLASTFUR with hydrogen    0.002562
                                                Biomass-based             0.002420
                                EAF with DRI    EAF with DRI              0.005170
                                                EAF with DRI CCS          0.000676
                                                Hydrogen-based DRI        0.001398
                                EAF with scrap  EAF with scrap            0.000399
          2045  iron and steel  BLASTFUR        BLASTFUR                  0.002248
                                                BLASTFUR CCS              0.000260
                                                BLASTFUR with hydrogen    0.002059
                                                Biomass-based             0.001954
                                EAF with DRI    EAF with DRI              0.004169
                                                EAF with DRI CCS          0.000510
                                                Hydrogen-based DRI        0.001059
                                EAF with scrap  EAF with scrap            0.000278
          2050  iron and steel  BLASTFUR        BLASTFUR                  0.001648
                                                BLASTFUR CCS              0.000173
                                                BLASTFUR with hydrogen    0.001500
                                                Biomass-based             0.001431
                                EAF with DRI    EAF with DRI              0.003051
                                                EAF with DRI CCS          0.000354
                                                Hydrogen-based DRI        0.000720
                                EAF with scrap  EAF with scrap            0.000178
dtype: float64

In [39]:
df_use = arrUse.reset_index()
df_use.columns

Index(['scenario', 'Year', 'sector', 'subsector', 'technology', 0], dtype='object')

In [40]:
# df_use['scenario'] = 'R65'
df_use.pivot(index=['scenario', 'Year'], columns=['sector', 'technology'], values=0)

sector        iron and steel                                      \
technology          BLASTFUR BLASTFUR CCS BLASTFUR with hydrogen
scenario Year
Baseline 2030       0.001103     0.000197               0.001038
         2035       0.002933     0.000434               0.002727
         2040       0.002782     0.000359               0.002562
         2045       0.002248     0.000260               0.002059
         2050       0.001648     0.000173               0.001500

sector                                                                        \
technology    Biomass-based EAF with DRI EAF with DRI CCS Hydrogen-based DRI
scenario Year
Baseline 2030      0.000963     0.002066         0.000333           0.000696
         2035      0.002556     0.005467         0.000779           0.001630
         2040      0.002420     0.005170         0.000676           0.001398
         2045      0.001954     0.004169         0.000510           0.001059
         2050      0.001431     0.003051         0.000354           0.000720

sector
technology    EAF with scrap
scenario Year
Baseline 2030       0.000239
         2035       0.000503
         2040       0.000399
         2045       0.000278
         2050       0.000178

In [41]:
region_name = "South Korea"

# Filter out NaN values if needed
df_use = arrUse.reset_index()
df_use.columns = ['scenario', 'Year', 'sector', 'subsector', 'technology', 'value']
df_use = df_use[(~df_use['value'].isna()) & (df_use['subsector'] != 'biomass')].copy()

# -----------------------------------------------------------
# 1. XML ROOT: <scenario>
# -----------------------------------------------------------
root = ET.Element("scenario")

# -----------------------------------------------------------
# 2. Add <world> and <region>
# -----------------------------------------------------------
world_el = ET.SubElement(root, "world")

region_el = ET.SubElement(world_el, "region")
region_el.set("name", region_name)

In [42]:
for sector_name in df_use['sector'].unique():
    supplysector_el = ET.SubElement(region_el, "supplysector")
    supplysector_el.set("name", sector_name)

    df_sector = df_use[df_use['sector'] == sector_name]

    for subsector_name in df_sector['subsector'].unique():
        subsector_el = ET.SubElement(supplysector_el, "subsector")
        subsector_el.set("name", subsector_name)

        df_sub = df_sector[df_sector['subsector'] == subsector_name]

        for tech_name in df_sub['technology'].unique():
            tech_el = ET.SubElement(subsector_el, "stub-technology")
            tech_el.set("name", tech_name)

            df_tech = df_sub[df_sub['technology'] == tech_name]

            for _, row in df_tech.iterrows():
                year = int(row['Year'])
                val = float(row['value'])

                period_el = ET.SubElement(tech_el, "period")
                period_el.set("year", str(year))

                # NEW BLOCK:
                non_energy_el = ET.SubElement(period_el, "minicam-non-energy-input")
                non_energy_el.set("name", "IronSteel-CBAM")

                input_cost_el = ET.SubElement(non_energy_el, "input-cost")
                input_cost_el.text = f"{val:.4f}"

In [43]:
# Convert raw to string
rough = ET.tostring(root, encoding="utf-8")

# Pretty formatting
pretty = minidom.parseString(rough).toprettyxml(indent="  ")

# Save
with open("../input/policy/industry/ironsteel_cbam_ERT_Baseline.xml", "w", encoding="utf-8") as f:
    f.write(pretty)

In [44]:
arrCO2ChemDirect = dfCO2[(dfCO2['sector'].str.contains('chemical')) & (dfCO2['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrCO2ChemDirect

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                 0.472477
                                                      biomass CCS             0.001577
                                     coal             coal                    0.082573
                                                      coal CCS                0.000064
                                     gas              gas                     0.516707
                                                      gas CCS                 0.000891
                                     refined liquids  refined liquids         1.496917
                                                      refined liquids CCS     0.002238
                chemical feedstocks  coal             coal                    0.138162
                                     refined liquids  refined liquids        11.247400
          2035  chemical energy use  biomass          biomass                 0.492794
                                                      biomass CCS             0.005603
                                     coal             coal                    0.075945
                                                      coal CCS                0.000201
                                     gas              gas                     0.500593
                                                      gas CCS                 0.002591
                                     refined liquids  refined liquids         1.422561
                                                      refined liquids CCS     0.006348
                chemical feedstocks  coal             coal                    0.141969
                                     refined liquids  refined liquids        11.577800
          2040  chemical energy use  biomass          biomass                 0.491782
                                                      biomass CCS             0.021257
                                     coal             coal                    0.056021
                                                      coal CCS                0.000632
                                     gas              gas                     0.426388
                                                      gas CCS                 0.007590
                                     refined liquids  refined liquids         1.161172
                                                      refined liquids CCS     0.018601
                chemical feedstocks  coal             coal                    0.137072
                                     refined liquids  refined liquids        11.583600
          2045  chemical energy use  biomass          biomass                 0.454024
                                                      biomass CCS             0.050540
                                     coal             coal                    0.030516
                                                      coal CCS                0.001299
                                     gas              gas                     0.320592
                                                      gas CCS                 0.015242
                                     refined liquids  refined liquids         0.810155
                                                      refined liquids CCS     0.037254
                chemical feedstocks  coal             coal                    0.126775
                                     refined liquids  refined liquids        11.315400
          2050  chemical energy use  biomass          biomass                 0.397926
                                                      biomass CCS             0.066905
                                     coal             coal                    0.016893
                                                      coal CCS                0.001713
                                     gas              gas                     0.255895
                                                      gas CCS                 0.020228
                                     refined liquids  refined liquids         0.607893
                                                      refined liquids CCS     0.049074
                chemical feedstocks  coal             coal                    0.115617
                                     refined liquids  refined liquids        10.994000
Name: value, dtype: float64

In [45]:
dfInput = run_query(conn=conn, q_idx=100, scenarios=['Baseline'], regions=['South Korea'])
dfInputIndirect = dfInput[(dfInput['sector'].str.contains('chemical')) & (dfInput['Year'] >= 2030)].copy()
df_indirect = (
    dfInputIndirect
    .merge(df_ci, on=["input", "Year"], how="left")
)
df_indirect["indirect_emissions_MtC"] = (
    df_indirect["value"] * df_indirect["ci"]
)
df_indirect
arrCO2ChemIndirect = df_indirect.groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['indirect_emissions_MtC'].sum()
arrCO2ChemIndirect

industry final energy by tech and fuel

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                0.000000
                                                      biomass CCS            0.000000
                                     coal             coal                   0.000000
                                                      coal CCS               0.000000
                                     electricity      electricity            3.932086
                                     gas              gas                    0.000000
                                                      gas CCS                0.000000
                                     refined liquids  refined liquids        0.000000
                                                      refined liquids CCS    0.000000
                chemical feedstocks  coal             coal                   0.000000
                                     refined liquids  refined liquids        0.000000
          2035  chemical energy use  biomass          biomass                0.000000
                                                      biomass CCS            0.000000
                                     coal             coal                   0.000000
                                                      coal CCS               0.000000
                                     electricity      electricity            2.999873
                                     gas              gas                    0.000000
                                                      gas CCS                0.000000
                                     refined liquids  refined liquids        0.000000
                                                      refined liquids CCS    0.000000
                chemical feedstocks  coal             coal                   0.000000
                                     refined liquids  refined liquids        0.000000
          2040  chemical energy use  biomass          biomass                0.000000
                                                      biomass CCS            0.000000
                                     coal             coal                   0.000000
                                                      coal CCS               0.000000
                                     electricity      electricity            2.616556
                                     gas              gas                    0.000000
                                                      gas CCS                0.000000
                                     refined liquids  refined liquids        0.000000
                                                      refined liquids CCS    0.000000
                chemical feedstocks  coal             coal                   0.000000
                                     refined liquids  refined liquids        0.000000
          2045  chemical energy use  biomass          biomass                0.000000
                                                      biomass CCS            0.000000
                                     coal             coal                   0.000000
                                                      coal CCS               0.000000
                                     electricity      electricity            2.326812
                                     gas              gas                    0.000000
                                                      gas CCS                0.000000
                                     refined liquids  refined liquids        0.000000
                                                      refined liquids CCS    0.000000
                chemical feedstocks  coal             coal                   0.000000
                                     refined liquids  refined liquids        0.000000
          2050  chemical energy use  biomass          biomass                0.000000
                                                      biomass CCS            0.000000
                                     coal             coal                   0.000000
                                                      coal CCS               0.000000
                                     electricity      electricity            1.826498
                                     gas              gas                    0.000000
                                                      gas CCS                0.000000
                                     refined liquids  refined liquids        0.000000
                                                      refined liquids CCS    0.000000
                chemical feedstocks  coal             coal                   0.000000
                                     refined liquids  refined liquids        0.000000
Name: indirect_emissions_MtC, dtype: float64

In [46]:
arrCO2Chem = arrCO2ChemIndirect.add(arrCO2ChemDirect, fill_value=0)
arrCO2Chem

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                 0.472477
                                                      biomass CCS             0.001577
                                     coal             coal                    0.082573
                                                      coal CCS                0.000064
                                     electricity      electricity             3.932086
                                     gas              gas                     0.516707
                                                      gas CCS                 0.000891
                                     refined liquids  refined liquids         1.496917
                                                      refined liquids CCS     0.002238
                chemical feedstocks  coal             coal                    0.138162
                                     refined liquids  refined liquids        11.247400
          2035  chemical energy use  biomass          biomass                 0.492794
                                                      biomass CCS             0.005603
                                     coal             coal                    0.075945
                                                      coal CCS                0.000201
                                     electricity      electricity             2.999873
                                     gas              gas                     0.500593
                                                      gas CCS                 0.002591
                                     refined liquids  refined liquids         1.422561
                                                      refined liquids CCS     0.006348
                chemical feedstocks  coal             coal                    0.141969
                                     refined liquids  refined liquids        11.577800
          2040  chemical energy use  biomass          biomass                 0.491782
                                                      biomass CCS             0.021257
                                     coal             coal                    0.056021
                                                      coal CCS                0.000632
                                     electricity      electricity             2.616556
                                     gas              gas                     0.426388
                                                      gas CCS                 0.007590
                                     refined liquids  refined liquids         1.161172
                                                      refined liquids CCS     0.018601
                chemical feedstocks  coal             coal                    0.137072
                                     refined liquids  refined liquids        11.583600
          2045  chemical energy use  biomass          biomass                 0.454024
                                                      biomass CCS             0.050540
                                     coal             coal                    0.030516
                                                      coal CCS                0.001299
                                     electricity      electricity             2.326812
                                     gas              gas                     0.320592
                                                      gas CCS                 0.015242
                                     refined liquids  refined liquids         0.810155
                                                      refined liquids CCS     0.037254
                chemical feedstocks  coal             coal                    0.126775
                                     refined liquids  refined liquids        11.315400
          2050  chemical energy use  biomass          biomass                 0.397926
                                                      biomass CCS             0.066905
                                     coal             coal                    0.016893
                                                      coal CCS                0.001713
                                     electricity      electricity             1.826498
                                     gas              gas                     0.255895
                                                      gas CCS                 0.020228
                                     refined liquids  refined liquids         0.607893
                                                      refined liquids CCS     0.049074
                chemical feedstocks  coal             coal                    0.115617
                                     refined liquids  refined liquids        10.994000
dtype: float64

In [47]:
dfChemTech = run_query(conn=conn, q_idx=100, scenarios=['Baseline'], regions=['South Korea'])
arrChemTech = dfChemTech[(dfChemTech['sector'].str.contains('chemical')) & (dfChemTech['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrChemTech

industry final energy by tech and fuel

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                0.020543
                                                      biomass CCS            0.000686
                                     coal             coal                   0.003025
                                                      coal CCS               0.000023
                                     electricity      electricity            0.226206
                                     gas              gas                    0.036388
                                                      gas CCS                0.000628
                                     refined liquids  refined liquids        0.076373
                                                      refined liquids CCS    0.001142
                chemical feedstocks  coal             coal                   0.020244
                                     refined liquids  refined liquids        2.295380
          2035  chemical energy use  biomass          biomass                0.021426
                                                      biomass CCS            0.002436
                                     coal             coal                   0.002782
                                                      coal CCS               0.000073
                                     electricity      electricity            0.254069
                                     gas              gas                    0.035253
                                                      gas CCS                0.001825
                                     refined liquids  refined liquids        0.072580
                                                      refined liquids CCS    0.003239
                chemical feedstocks  coal             coal                   0.020801
                                     refined liquids  refined liquids        2.362810
          2040  chemical energy use  biomass          biomass                0.021382
                                                      biomass CCS            0.009242
                                     coal             coal                   0.002052
                                                      coal CCS               0.000232
                                     electricity      electricity            0.309894
                                     gas              gas                    0.030027
                                                      gas CCS                0.005345
                                     refined liquids  refined liquids        0.059243
                                                      refined liquids CCS    0.009490
                chemical feedstocks  coal             coal                   0.020084
                                     refined liquids  refined liquids        2.364010
          2045  chemical energy use  biomass          biomass                0.019740
                                                      biomass CCS            0.021974
                                     coal             coal                   0.001118
                                                      coal CCS               0.000476
                                     electricity      electricity            0.381861
                                     gas              gas                    0.022577
                                                      gas CCS                0.010733
                                     refined liquids  refined liquids        0.041334
                                                      refined liquids CCS    0.019007
                chemical feedstocks  coal             coal                   0.018575
                                     refined liquids  refined liquids        2.309260
          2050  chemical energy use  biomass          biomass                0.017301
                                                      biomass CCS            0.029089
                                     coal             coal                   0.000619
                                                      coal CCS               0.000628
                                     electricity      electricity            0.426197
                                     gas              gas                    0.018021
                                                      gas CCS                0.014245
                                     refined liquids  refined liquids        0.031015
                                                      refined liquids CCS    0.025038
                chemical feedstocks  coal             coal                   0.016940
                                     refined liquids  refined liquids        2.243670
Name: value, dtype: float64

In [48]:
arrTax = dfTax[(dfTax.index >= 2030)]['D'] # 1990$ / tC
arrTax

Year
2030    115.2090
2035    311.6911
2040    298.7602
2045    243.2190
2050    179.3534
Name: D, dtype: float64

In [49]:
arrCO2I = (arrCO2Chem / arrChemTech) # MTC / EJ
arrCO2I

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                22.999981
                                                      biomass CCS             2.299996
                                     coal             coal                   27.299984
                                                      coal CCS                2.729998
                                     electricity      electricity            17.382774
                                     gas              gas                    14.200001
                                                      gas CCS                 1.420001
                                     refined liquids  refined liquids        19.600036
                                                      refined liquids CCS     1.960003
                chemical feedstocks  coal             coal                    6.825006
                                     refined liquids  refined liquids         4.900017
          2035  chemical energy use  biomass          biomass                22.999999
                                                      biomass CCS             2.299998
                                     coal             coal                   27.300045
                                                      coal CCS                2.730000
                                     electricity      electricity            11.807305
                                     gas              gas                    14.200004
                                                      gas CCS                 1.419999
                                     refined liquids  refined liquids        19.599998
                                                      refined liquids CCS     1.959998
                chemical feedstocks  coal             coal                    6.825006
                                     refined liquids  refined liquids         4.900013
          2040  chemical energy use  biomass          biomass                23.000050
                                                      biomass CCS             2.299995
                                     coal             coal                   27.299968
                                                      coal CCS                2.730003
                                     electricity      electricity             8.443401
                                     gas              gas                    14.200008
                                                      gas CCS                 1.420001
                                     refined liquids  refined liquids        19.600005
                                                      refined liquids CCS     1.959995
                chemical feedstocks  coal             coal                    6.825003
                                     refined liquids  refined liquids         4.899979
          2045  chemical energy use  biomass          biomass                22.999990
                                                      biomass CCS             2.299995
                                     coal             coal                   27.299997
                                                      coal CCS                2.729995
                                     electricity      electricity             6.093347
                                     gas              gas                    14.200012
                                                      gas CCS                 1.420001
                                     refined liquids  refined liquids        19.600014
                                                      refined liquids CCS     1.959997
                chemical feedstocks  coal             coal                    6.824997
                                     refined liquids  refined liquids         4.900011
          2050  chemical energy use  biomass          biomass                23.000052
                                                      biomass CCS             2.299996
                                     coal             coal                   27.300027
                                                      coal CCS                2.729996
                                     electricity      electricity             4.285575
                                     gas              gas                    14.200001
                                                      gas CCS                 1.420000
                                     refined liquids  refined liquids        19.599996
                                                      refined liquids CCS     1.960002
                chemical feedstocks  coal             coal                    6.825008
                                     refined liquids  refined liquids         4.900008
dtype: float64

In [50]:
dfCo2I = (arrCO2I * 44/12 / 1000).reset_index()
dfCo2I = dfCo2I[(dfCo2I['Year'].isin([2035, 2050])) & (dfCo2I['subsector'] != 'biomass')].pivot(index=['sector', 'subsector', 'technology'], columns='Year', values=0).reset_index()
dfCo2I['unit'] = 'tCO2 / GJ'
dfCo2I['sector'] = 'chemicals'
dfCo2I.to_csv("./output/chemiclas_carbon_intensity.csv", index=False)
dfCo2I

Year,sector,subsector,technology,2035,2050,unit
0,chemicals,coal,coal,0.100100,0.100100,tCO2 / GJ
1,chemicals,coal,coal CCS,0.010010,0.010010,tCO2 / GJ
2,chemicals,electricity,electricity,0.043293,0.015714,tCO2 / GJ
3,chemicals,gas,gas,0.052067,0.052067,tCO2 / GJ
4,chemicals,gas,gas CCS,0.005207,0.005207,tCO2 / GJ
5,chemicals,refined liquids,refined liquids,0.071867,0.071867,tCO2 / GJ
6,chemicals,refined liquids,refined liquids CCS,0.007187,0.007187,tCO2 / GJ
7,chemicals,coal,coal,0.025025,0.025025,tCO2 / GJ
8,chemicals,refined liquids,refined liquids,0.017967,0.017967,tCO2 / GJ

In [51]:
ALPHA_EU_CHEMICAL = (4.812/159.5)
arrUse = ALPHA_EU_CHEMICAL * arrCO2I * arrTax * CONVERT_1990_TO_1975 / 1000 # (1975$/1990$) * (1990$ / tC) * (MTC / EJ) / 1000 = 1975$ / GJ
arrUse

scenario  Year  sector               subsector        technology
Baseline  2030  chemical energy use  biomass          biomass                0.037470
                                                      biomass CCS            0.003747
                                     coal             coal                   0.044475
                                                      coal CCS               0.004448
                                     electricity      electricity            0.028319
                                     gas              gas                    0.023134
                                                      gas CCS                0.002313
                                     refined liquids  refined liquids        0.031931
                                                      refined liquids CCS    0.003193
                chemical feedstocks  coal             coal                   0.011119
                                     refined liquids  refined liquids        0.007983
          2035  chemical energy use  biomass          biomass                0.101373
                                                      biomass CCS            0.010137
                                     coal             coal                   0.120326
                                                      coal CCS               0.012033
                                     electricity      electricity            0.052041
                                     gas              gas                    0.062587
                                                      gas CCS                0.006259
                                     refined liquids  refined liquids        0.086388
                                                      refined liquids CCS    0.008639
                chemical feedstocks  coal             coal                   0.030081
                                     refined liquids  refined liquids        0.021597
          2040  chemical energy use  biomass          biomass                0.097168
                                                      biomass CCS            0.009717
                                     coal             coal                   0.115334
                                                      coal CCS               0.011533
                                     electricity      electricity            0.035671
                                     gas              gas                    0.059991
                                                      gas CCS                0.005999
                                     refined liquids  refined liquids        0.082804
                                                      refined liquids CCS    0.008280
                chemical feedstocks  coal             coal                   0.028833
                                     refined liquids  refined liquids        0.020701
          2045  chemical energy use  biomass          biomass                0.079104
                                                      biomass CCS            0.007910
                                     coal             coal                   0.093893
                                                      coal CCS               0.009389
                                     electricity      electricity            0.020957
                                     gas              gas                    0.048838
                                                      gas CCS                0.004884
                                     refined liquids  refined liquids        0.067410
                                                      refined liquids CCS    0.006741
                chemical feedstocks  coal             coal                   0.023473
                                     refined liquids  refined liquids        0.016853
          2050  chemical energy use  biomass          biomass                0.058332
                                                      biomass CCS            0.005833
                                     coal             coal                   0.069238
                                                      coal CCS               0.006924
                                     electricity      electricity            0.010869
                                     gas              gas                    0.036014
                                                      gas CCS                0.003601
                                     refined liquids  refined liquids        0.049709
                                                      refined liquids CCS    0.004971
                chemical feedstocks  coal             coal                   0.017309
                                     refined liquids  refined liquids        0.012427
dtype: float64

In [52]:
df_use = arrUse.reset_index()
df_use.columns

Index(['scenario', 'Year', 'sector', 'subsector', 'technology', 0], dtype='object')

In [53]:
df_use['scenario'] = 'Baseline'
df_use.pivot(index=['scenario', 'Year'], columns=['sector', 'technology'], values=0)

sector        chemical energy use                                              \
technology                biomass biomass CCS      coal  coal CCS electricity
scenario Year
Baseline 2030            0.037470    0.003747  0.044475  0.004448    0.028319
         2035            0.101373    0.010137  0.120326  0.012033    0.052041
         2040            0.097168    0.009717  0.115334  0.011533    0.035671
         2045            0.079104    0.007910  0.093893  0.009389    0.020957
         2050            0.058332    0.005833  0.069238  0.006924    0.010869

sector                                                                 \
technology          gas   gas CCS refined liquids refined liquids CCS
scenario Year
Baseline 2030  0.023134  0.002313        0.031931            0.003193
         2035  0.062587  0.006259        0.086388            0.008639
         2040  0.059991  0.005999        0.082804            0.008280
         2045  0.048838  0.004884        0.067410            0.006741
         2050  0.036014  0.003601        0.049709            0.004971

sector        chemical feedstocks
technology                   coal refined liquids
scenario Year
Baseline 2030            0.011119        0.007983
         2035            0.030081        0.021597
         2040            0.028833        0.020701
         2045            0.023473        0.016853
         2050            0.017309        0.012427

In [54]:
region_name = "South Korea"

# Filter out NaN values if needed
df_use = arrUse.reset_index()
df_use.columns = ['scenario', 'Year', 'sector', 'subsector', 'technology', 'value']
df_use = df_use[(~df_use['value'].isna()) & (df_use['subsector'] != 'biomass')].copy()

# -----------------------------------------------------------
# 1. XML ROOT: <scenario>
# -----------------------------------------------------------
root = ET.Element("scenario")

# -----------------------------------------------------------
# 2. Add <world> and <region>
# -----------------------------------------------------------
world_el = ET.SubElement(root, "world")

region_el = ET.SubElement(world_el, "region")
region_el.set("name", region_name)

In [55]:
for sector_name in df_use['sector'].unique():
    supplysector_el = ET.SubElement(region_el, "supplysector")
    supplysector_el.set("name", sector_name)

    df_sector = df_use[df_use['sector'] == sector_name]

    for subsector_name in df_sector['subsector'].unique():
        subsector_el = ET.SubElement(supplysector_el, "subsector")
        subsector_el.set("name", subsector_name)

        df_sub = df_sector[df_sector['subsector'] == subsector_name]

        for tech_name in df_sub['technology'].unique():
            tech_el = ET.SubElement(subsector_el, "stub-technology")
            tech_el.set("name", tech_name)

            df_tech = df_sub[df_sub['technology'] == tech_name]

            for _, row in df_tech.iterrows():
                year = int(row['Year'])
                val = float(row['value'])

                period_el = ET.SubElement(tech_el, "period")
                period_el.set("year", str(year))

                # NEW BLOCK:
                non_energy_el = ET.SubElement(period_el, "minicam-non-energy-input")
                non_energy_el.set("name", "Chemical-CBAM")

                input_cost_el = ET.SubElement(non_energy_el, "input-cost")
                input_cost_el.text = f"{val:.4f}"

In [56]:
# Convert raw to string
rough = ET.tostring(root, encoding="utf-8")

# Pretty formatting
pretty = minidom.parseString(rough).toprettyxml(indent="  ")

# Save
with open("../input/policy/industry/chemical_cbam_ERT_Baseline.xml", "w", encoding="utf-8") as f:
    f.write(pretty)

# Competitiveness Erosion

In [57]:
scenario = ['Competitiveness-Erosion']
dfTax = run_query(conn=conn, q_idx=297, scenarios=scenario)
dfTax = dfTax[(dfTax['Year'] <= 2050) & (dfTax['Year'] >= 2021) & (dfTax['market'].isin(['EU-27CO2', 'South KoreaCO2']))].pivot(index='Year', columns='market', values='value').copy()
dfTax['St_EU'] = [0, 0, 0.485, 1, 1, 1, 1]
dfTax['St_KOR'] = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
dfTax['P_EU_eff'] = dfTax['St_EU'] * dfTax['EU-27CO2']
dfTax['P_KOR_eff'] = dfTax['St_KOR'] * dfTax['South KoreaCO2']
dfTax['D'] = (dfTax['P_EU_eff'] - dfTax['P_KOR_eff'])
dfTax

CO2 prices

market,EU-27CO2,South KoreaCO2,St_EU,St_KOR,P_EU_eff,P_KOR_eff,D
Year,,,,,,,
2021,0.000,0.000,0.000,0.0,0.000000,0.0000,0.000000
2025,251.751,187.719,0.000,0.1,0.000000,18.7719,-18.771900
2030,335.595,220.834,0.485,0.2,162.763575,44.1668,118.596775
2035,392.603,237.444,1.000,0.3,392.603000,71.2332,321.369800
2040,422.098,260.696,1.000,0.4,422.098000,104.2784,317.819600
2045,414.276,297.039,1.000,0.5,414.276000,148.5195,265.756500
2050,398.425,353.486,1.000,0.6,398.425000,212.0916,186.333400

In [58]:
dfCO2 = run_query(conn=conn, q_idx=268, scenarios=scenario, regions=['South Korea'])
dfCO2

CO2 emissions by tech (excluding resource production)

,Units,scenario,region,sector,subsector,technology,Year,value
0,MTC,Competitiveness-Erosion,South Korea,H2 central production,biomass,biomass to H2,2025,0.001075
1,MTC,Competitiveness-Erosion,South Korea,H2 central production,biomass,biomass to H2,2030,0.030366
2,MTC,Competitiveness-Erosion,South Korea,H2 central production,biomass,biomass to H2,2035,0.081044
3,MTC,Competitiveness-Erosion,South Korea,H2 central production,biomass,biomass to H2,2040,0.151755
4,MTC,Competitiveness-Erosion,South Korea,H2 central production,biomass,biomass to H2,2045,0.171024
...,...,...,...,...,...,...,...,...
1982,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,biomass,biomass cogen,2030,0.154050
1983,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,biomass,biomass cogen,2035,0.156608
1984,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,biomass,biomass cogen,2040,0.164098
1985,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,biomass,biomass cogen,2045,0.170924
1986,MTC,Competitiveness-Erosion,South Korea,waste biomass for paper,biomass,biomass cogen,2050,0.168164

In [59]:
arrCO2SteelDirect = dfCO2[(dfCO2['sector'].str.contains('iron and steel')) & (dfCO2['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrCO2SteelDirect

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  17.174070
                                                               BLASTFUR CCS               0.045053
                                                               BLASTFUR with hydrogen     0.114041
                                                               Biomass-based              0.425098
                                               EAF with DRI    EAF with DRI               0.534154
                                                               EAF with DRI CCS           0.004922
                                               EAF with scrap  EAF with scrap             0.717517
                         2035  iron and steel  BLASTFUR        BLASTFUR                  13.209090
                                                               BLASTFUR CCS               0.195884
                                                               BLASTFUR with hydrogen     0.325668
                                                               Biomass-based              1.223266
                                               EAF with DRI    EAF with DRI               0.946497
                                                               EAF with DRI CCS           0.028955
                                               EAF with scrap  EAF with scrap             0.844107
                         2040  iron and steel  BLASTFUR        BLASTFUR                   9.273908
                                                               BLASTFUR CCS               0.349478
                                                               BLASTFUR with hydrogen     0.458636
                                                               Biomass-based              1.753917
                                               EAF with DRI    EAF with DRI               1.198518
                                                               EAF with DRI CCS           0.062185
                                               EAF with scrap  EAF with scrap             0.903025
                         2045  iron and steel  BLASTFUR        BLASTFUR                   7.812130
                                                               BLASTFUR CCS               0.427577
                                                               BLASTFUR with hydrogen     0.459623
                                                               Biomass-based              1.827477
                                               EAF with DRI    EAF with DRI               1.179396
                                                               EAF with DRI CCS           0.090065
                                               EAF with scrap  EAF with scrap             0.897065
                         2050  iron and steel  BLASTFUR        BLASTFUR                   6.078568
                                                               BLASTFUR CCS               0.527890
                                                               BLASTFUR with hydrogen     0.435162
                                                               Biomass-based              1.808263
                                               EAF with DRI    EAF with DRI               1.076444
                                                               EAF with DRI CCS           0.137308
                                               EAF with scrap  EAF with scrap             0.898205
Name: value, dtype: float64

In [60]:
dfElec = run_query(conn=conn, q_idx=8, scenarios=scenario, regions=['South Korea'])
dfElec.groupby('Year')['value'].sum()

elec gen by subsector

Year
1990    0.358142
2005    1.313811
2010    1.696271
2015    1.879333
2021    2.076581
2025    2.199723
2030    2.358601
2035    2.541289
2040    2.733135
2045    2.891292
2050    2.937285
Name: value, dtype: float64

In [61]:
dfCO2[(dfCO2['sector'].str.contains('elec'))].groupby('Year')['value'].sum()

Year
1990     9.396560
2005    47.407164
2010    67.239118
2015    69.733274
2021    68.565066
2025    55.276003
2030    43.328389
2035    33.619166
2040    27.394772
2045    20.584454
2050    12.848881
Name: value, dtype: float64

In [62]:
arrElecI = dfCO2[(dfCO2['Year'] >= 2030) & (dfCO2['sector'].str.contains('elec'))].groupby('Year')['value'].sum() / dfElec[(dfElec['Year'] >= 2030)].groupby('Year')['value'].sum()
arrElecI

Year
2030    18.370376
2035    13.229176
2040    10.023203
2045     7.119466
2050     4.374407
Name: value, dtype: float64

In [63]:
dfH2 = run_query(conn=conn, q_idx=45, scenarios=scenario, regions=['South Korea'])
dfH2.groupby('Year')['value'].sum()

hydrogen production by tech

Year
2025    0.000249
2030    0.011282
2035    0.039835
2040    0.093237
2045    0.130608
2050    0.160300
Name: value, dtype: float64

In [64]:
dfCO2[(dfCO2['sector'].str.contains('H2'))].groupby('Year')['value'].sum()

Year
2025    0.004918
2030    0.191975
2035    0.623254
2040    1.371646
2045    1.852527
2050    2.141877
Name: value, dtype: float64

In [65]:
arrH2I = dfCO2[(dfCO2['Year'] >= 2030) & (dfCO2['sector'].str.contains('H2'))].groupby('Year')['value'].sum() / dfH2[(dfH2['Year'] >= 2030)].groupby('Year')['value'].sum()
arrH2I

Year
2030    17.015326
2035    15.645864
2040    14.711396
2045    14.183864
2050    13.361679
Name: value, dtype: float64

In [66]:
dfElecI = arrElecI.reset_index()
dfElecI['input'] = 'elect_td_ind'
dfElecI

   Year      value         input
0  2030  18.370376  elect_td_ind
1  2035  13.229176  elect_td_ind
2  2040  10.023203  elect_td_ind
3  2045   7.119466  elect_td_ind
4  2050   4.374407  elect_td_ind

In [67]:
dfH2I = arrH2I.reset_index()
dfH2I['input'] = 'H2 industrial'
dfH2I

   Year      value          input
0  2030  17.015326  H2 industrial
1  2035  15.645864  H2 industrial
2  2040  14.711396  H2 industrial
3  2045  14.183864  H2 industrial
4  2050  13.361679  H2 industrial

In [68]:
df_ci = pd.concat([dfElecI, dfH2I], axis=0).rename(columns={'value': 'ci'})
df_ci

   Year         ci          input
0  2030  18.370376   elect_td_ind
1  2035  13.229176   elect_td_ind
2  2040  10.023203   elect_td_ind
3  2045   7.119466   elect_td_ind
4  2050   4.374407   elect_td_ind
0  2030  17.015326  H2 industrial
1  2035  15.645864  H2 industrial
2  2040  14.711396  H2 industrial
3  2045  14.183864  H2 industrial
4  2050  13.361679  H2 industrial

In [69]:
dfInput = run_query(conn=conn, q_idx=100, scenarios=scenario, regions=['South Korea'])
dfInputIndirect = dfInput[(dfInput['sector'] == 'iron and steel') & (dfInput['input'].isin(['elect_td_ind', 'H2 industrial'])) & (dfInput['Year'] >= 2030)].copy()
df_indirect = (
    dfInputIndirect
    .merge(df_ci, on=["input", "Year"], how="left")
)
df_indirect["indirect_emissions_MtC"] = (
    df_indirect["value"] * df_indirect["ci"]
)
df_indirect
arrCO2SteelIndirect = df_indirect.groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['indirect_emissions_MtC'].sum()
arrCO2SteelIndirect

industry final energy by tech and fuel

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  1.016781
                                                               BLASTFUR CCS              0.064665
                                                               BLASTFUR with hydrogen    0.025916
                                                               Biomass-based             0.029048
                                               EAF with DRI    EAF with DRI              0.041144
                                                               EAF with DRI CCS          0.003791
                                                               Hydrogen-based DRI        0.014773
                                               EAF with scrap  EAF with scrap            1.697823
                         2035  iron and steel  BLASTFUR        BLASTFUR                  0.563172
                                                               BLASTFUR CCS              0.202474
                                                               BLASTFUR with hydrogen    0.063332
                                                               Biomass-based             0.060196
                                               EAF with DRI    EAF with DRI              0.052501
                                                               EAF with DRI CCS          0.016061
                                                               Hydrogen-based DRI        0.052038
                                               EAF with scrap  EAF with scrap            1.438377
                         2040  iron and steel  BLASTFUR        BLASTFUR                  0.299575
                                                               BLASTFUR CCS              0.273691
                                                               BLASTFUR with hydrogen    0.079478
                                                               Biomass-based             0.065393
                                               EAF with DRI    EAF with DRI              0.050369
                                                               EAF with DRI CCS          0.026134
                                                               Hydrogen-based DRI        0.087106
                                               EAF with scrap  EAF with scrap            1.165866
                         2045  iron and steel  BLASTFUR        BLASTFUR                  0.179247
                                                               BLASTFUR CCS              0.237847
                                                               BLASTFUR with hydrogen    0.072165
                                                               Biomass-based             0.048396
                                               EAF with DRI    EAF with DRI              0.035207
                                                               EAF with DRI CCS          0.026886
                                                               Hydrogen-based DRI        0.105185
                                               EAF with scrap  EAF with scrap            0.822648
                         2050  iron and steel  BLASTFUR        BLASTFUR                  0.085695
                                                               BLASTFUR CCS              0.180425
                                                               BLASTFUR with hydrogen    0.060347
                                                               Biomass-based             0.029423
                                               EAF with DRI    EAF with DRI              0.019744
                                                               EAF with DRI CCS          0.025184
                                                               Hydrogen-based DRI        0.132465
                                               EAF with scrap  EAF with scrap            0.506101
Name: indirect_emissions_MtC, dtype: float64

In [70]:
arrCO2SteelDirect

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  17.174070
                                                               BLASTFUR CCS               0.045053
                                                               BLASTFUR with hydrogen     0.114041
                                                               Biomass-based              0.425098
                                               EAF with DRI    EAF with DRI               0.534154
                                                               EAF with DRI CCS           0.004922
                                               EAF with scrap  EAF with scrap             0.717517
                         2035  iron and steel  BLASTFUR        BLASTFUR                  13.209090
                                                               BLASTFUR CCS               0.195884
                                                               BLASTFUR with hydrogen     0.325668
                                                               Biomass-based              1.223266
                                               EAF with DRI    EAF with DRI               0.946497
                                                               EAF with DRI CCS           0.028955
                                               EAF with scrap  EAF with scrap             0.844107
                         2040  iron and steel  BLASTFUR        BLASTFUR                   9.273908
                                                               BLASTFUR CCS               0.349478
                                                               BLASTFUR with hydrogen     0.458636
                                                               Biomass-based              1.753917
                                               EAF with DRI    EAF with DRI               1.198518
                                                               EAF with DRI CCS           0.062185
                                               EAF with scrap  EAF with scrap             0.903025
                         2045  iron and steel  BLASTFUR        BLASTFUR                   7.812130
                                                               BLASTFUR CCS               0.427577
                                                               BLASTFUR with hydrogen     0.459623
                                                               Biomass-based              1.827477
                                               EAF with DRI    EAF with DRI               1.179396
                                                               EAF with DRI CCS           0.090065
                                               EAF with scrap  EAF with scrap             0.897065
                         2050  iron and steel  BLASTFUR        BLASTFUR                   6.078568
                                                               BLASTFUR CCS               0.527890
                                                               BLASTFUR with hydrogen     0.435162
                                                               Biomass-based              1.808263
                                               EAF with DRI    EAF with DRI               1.076444
                                                               EAF with DRI CCS           0.137308
                                               EAF with scrap  EAF with scrap             0.898205
Name: value, dtype: float64

In [71]:
arrCO2Steel = arrCO2SteelIndirect.add(arrCO2SteelDirect, fill_value=0)
arrCO2Steel

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  18.190851
                                                               BLASTFUR CCS               0.109718
                                                               BLASTFUR with hydrogen     0.139957
                                                               Biomass-based              0.454146
                                               EAF with DRI    EAF with DRI               0.575298
                                                               EAF with DRI CCS           0.008713
                                                               Hydrogen-based DRI         0.014773
                                               EAF with scrap  EAF with scrap             2.415340
                         2035  iron and steel  BLASTFUR        BLASTFUR                  13.772262
                                                               BLASTFUR CCS               0.398357
                                                               BLASTFUR with hydrogen     0.389001
                                                               Biomass-based              1.283462
                                               EAF with DRI    EAF with DRI               0.998998
                                                               EAF with DRI CCS           0.045016
                                                               Hydrogen-based DRI         0.052038
                                               EAF with scrap  EAF with scrap             2.282484
                         2040  iron and steel  BLASTFUR        BLASTFUR                   9.573483
                                                               BLASTFUR CCS               0.623169
                                                               BLASTFUR with hydrogen     0.538115
                                                               Biomass-based              1.819310
                                               EAF with DRI    EAF with DRI               1.248887
                                                               EAF with DRI CCS           0.088320
                                                               Hydrogen-based DRI         0.087106
                                               EAF with scrap  EAF with scrap             2.068890
                         2045  iron and steel  BLASTFUR        BLASTFUR                   7.991377
                                                               BLASTFUR CCS               0.665424
                                                               BLASTFUR with hydrogen     0.531788
                                                               Biomass-based              1.875873
                                               EAF with DRI    EAF with DRI               1.214602
                                                               EAF with DRI CCS           0.116951
                                                               Hydrogen-based DRI         0.105185
                                               EAF with scrap  EAF with scrap             1.719713
                         2050  iron and steel  BLASTFUR        BLASTFUR                   6.164263
                                                               BLASTFUR CCS               0.708315
                                                               BLASTFUR with hydrogen     0.495508
                                                               Biomass-based              1.837686
                                               EAF with DRI    EAF with DRI               1.096188
                                                               EAF with DRI CCS           0.162492
                                                               Hydrogen-based DRI         0.132465
                                               EAF with scrap  EAF with scrap             1.404306
dtype: float64

In [72]:
dfSteelTech = run_query(conn=conn, q_idx=119, scenarios=scenario, regions=['South Korea'])
arrSteelTech = dfSteelTech[(dfSteelTech['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrSteelTech

iron and steel production by tech

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  38.503670
                                                               BLASTFUR CCS               1.265220
                                                               BLASTFUR with hydrogen     0.313990
                                                               Biomass-based              1.100000
                                               EAF with DRI    EAF with DRI               0.649555
                                                               EAF with DRI CCS           0.059855
                                                               Hydrogen-based DRI         0.048556
                                               EAF with scrap  EAF with scrap            22.779100
                         2035  iron and steel  BLASTFUR        BLASTFUR                  29.614280
                                                               BLASTFUR CCS               5.501050
                                                               BLASTFUR with hydrogen     0.896666
                                                               Biomass-based              3.165378
                                               EAF with DRI    EAF with DRI               1.150982
                                                               EAF with DRI CCS           0.352110
                                                               Hydrogen-based DRI         0.194286
                                               EAF with scrap  EAF with scrap            26.798050
                         2040  iron and steel  BLASTFUR        BLASTFUR                  20.791745
                                                               BLASTFUR CCS               9.814433
                                                               BLASTFUR with hydrogen     1.262767
                                                               Biomass-based              4.538521
                                               EAF with DRI    EAF with DRI               1.457450
                                                               EAF with DRI CCS           0.756203
                                                               Hydrogen-based DRI         0.357009
                                               EAF with scrap  EAF with scrap            28.668470
                         2045  iron and steel  BLASTFUR        BLASTFUR                  17.514490
                                                               BLASTFUR CCS              12.007746
                                                               BLASTFUR with hydrogen     1.265483
                                                               Biomass-based              4.728858
                                               EAF with DRI    EAF with DRI               1.434197
                                                               EAF with DRI CCS           1.095233
                                                               Hydrogen-based DRI         0.463441
                                               EAF with scrap  EAF with scrap            28.479350
                         2050  iron and steel  BLASTFUR        BLASTFUR                  13.627910
                                                               BLASTFUR CCS              14.824852
                                                               BLASTFUR with hydrogen     1.198134
                                                               Biomass-based              4.679145
                                               EAF with DRI    EAF with DRI               1.309004
                                                               EAF with DRI CCS           1.669725
                                                               Hydrogen-based DRI         0.642336
                                               EAF with scrap  EAF with scrap            28.515540
Name: value, dtype: float64

In [73]:
arrTax = dfTax[(dfTax.index >= 2030)]['D'] # 1990$ / tC
arrTax

Year
2030    118.596775
2035    321.369800
2040    317.819600
2045    265.756500
2050    186.333400
Name: D, dtype: float64

In [74]:
arrCO2I = (arrCO2Steel / arrSteelTech) # MtC / Mt = tC / t
arrCO2I

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  0.472445
                                                               BLASTFUR CCS              0.086718
                                                               BLASTFUR with hydrogen    0.445739
                                                               Biomass-based             0.412860
                                               EAF with DRI    EAF with DRI              0.885679
                                                               EAF with DRI CCS          0.145575
                                                               Hydrogen-based DRI        0.304242
                                               EAF with scrap  EAF with scrap            0.106033
                         2035  iron and steel  BLASTFUR        BLASTFUR                  0.465055
                                                               BLASTFUR CCS              0.072415
                                                               BLASTFUR with hydrogen    0.433830
                                                               Biomass-based             0.405469
                                               EAF with DRI    EAF with DRI              0.867953
                                                               EAF with DRI CCS          0.127848
                                                               Hydrogen-based DRI        0.267844
                                               EAF with scrap  EAF with scrap            0.085174
                         2040  iron and steel  BLASTFUR        BLASTFUR                  0.460446
                                                               BLASTFUR CCS              0.063495
                                                               BLASTFUR with hydrogen    0.426139
                                                               Biomass-based             0.400860
                                               EAF with DRI    EAF with DRI              0.856899
                                                               EAF with DRI CCS          0.116794
                                                               Hydrogen-based DRI        0.243990
                                               EAF with scrap  EAF with scrap            0.072166
                         2045  iron and steel  BLASTFUR        BLASTFUR                  0.456272
                                                               BLASTFUR CCS              0.055416
                                                               BLASTFUR with hydrogen    0.420225
                                                               Biomass-based             0.396686
                                               EAF with DRI    EAF with DRI              0.846887
                                                               EAF with DRI CCS          0.106782
                                                               Hydrogen-based DRI        0.226966
                                               EAF with scrap  EAF with scrap            0.060385
                         2050  iron and steel  BLASTFUR        BLASTFUR                  0.452326
                                                               BLASTFUR CCS              0.047779
                                                               BLASTFUR with hydrogen    0.413567
                                                               Biomass-based             0.392740
                                               EAF with DRI    EAF with DRI              0.837421
                                                               EAF with DRI CCS          0.097317
                                                               Hydrogen-based DRI        0.206224
                                               EAF with scrap  EAF with scrap            0.049247
dtype: float64

In [75]:
ALPHA_EU_STEEL = (2.76/63.65) # 2024 Korea Iron and Steel Association (KOSA)
CONVERT_1990_TO_1975 = 31.01 / 66.16
arrUse = ALPHA_EU_STEEL * arrCO2I * arrTax * CONVERT_1990_TO_1975 / 1000 # (tC/t) * (1990$/tC) * (1975$/1990$) / (t/kg) = (1975$/kg)
arrUse

scenario                 Year  sector          subsector       technology
Competitiveness-Erosion  2030  iron and steel  BLASTFUR        BLASTFUR                  0.001139
                                                               BLASTFUR CCS              0.000209
                                                               BLASTFUR with hydrogen    0.001074
                                                               Biomass-based             0.000995
                                               EAF with DRI    EAF with DRI              0.002135
                                                               EAF with DRI CCS          0.000351
                                                               Hydrogen-based DRI        0.000733
                                               EAF with scrap  EAF with scrap            0.000256
                         2035  iron and steel  BLASTFUR        BLASTFUR                  0.003038
                                                               BLASTFUR CCS              0.000473
                                                               BLASTFUR with hydrogen    0.002834
                                                               Biomass-based             0.002648
                                               EAF with DRI    EAF with DRI              0.005669
                                                               EAF with DRI CCS          0.000835
                                                               Hydrogen-based DRI        0.001749
                                               EAF with scrap  EAF with scrap            0.000556
                         2040  iron and steel  BLASTFUR        BLASTFUR                  0.002974
                                                               BLASTFUR CCS              0.000410
                                                               BLASTFUR with hydrogen    0.002753
                                                               Biomass-based             0.002589
                                               EAF with DRI    EAF with DRI              0.005535
                                                               EAF with DRI CCS          0.000754
                                                               Hydrogen-based DRI        0.001576
                                               EAF with scrap  EAF with scrap            0.000466
                         2045  iron and steel  BLASTFUR        BLASTFUR                  0.002464
                                                               BLASTFUR CCS              0.000299
                                                               BLASTFUR with hydrogen    0.002270
                                                               Biomass-based             0.002143
                                               EAF with DRI    EAF with DRI              0.004574
                                                               EAF with DRI CCS          0.000577
                                                               Hydrogen-based DRI        0.001226
                                               EAF with scrap  EAF with scrap            0.000326
                         2050  iron and steel  BLASTFUR        BLASTFUR                  0.001713
                                                               BLASTFUR CCS              0.000181
                                                               BLASTFUR with hydrogen    0.001566
                                                               Biomass-based             0.001487
                                               EAF with DRI    EAF with DRI              0.003171
                                                               EAF with DRI CCS          0.000369
                                                               Hydrogen-based DRI        0.000781
                                               EAF with scrap  EAF with scrap            0.000187
dtype: float64

In [76]:
df_use = arrUse.reset_index()
df_use.columns

Index(['scenario', 'Year', 'sector', 'subsector', 'technology', 0], dtype='object')

In [77]:
# df_use['scenario'] = 'R65'
df_use.pivot(index=['scenario', 'Year'], columns=['sector', 'technology'], values=0)

sector                       iron and steel               \
technology                         BLASTFUR BLASTFUR CCS
scenario                Year
Competitiveness-Erosion 2030       0.001139     0.000209
                        2035       0.003038     0.000473
                        2040       0.002974     0.000410
                        2045       0.002464     0.000299
                        2050       0.001713     0.000181

sector                                                             \
technology                   BLASTFUR with hydrogen Biomass-based
scenario                Year
Competitiveness-Erosion 2030               0.001074      0.000995
                        2035               0.002834      0.002648
                        2040               0.002753      0.002589
                        2045               0.002270      0.002143
                        2050               0.001566      0.001487

sector                                                                         \
technology                   EAF with DRI EAF with DRI CCS Hydrogen-based DRI
scenario                Year
Competitiveness-Erosion 2030     0.002135         0.000351           0.000733
                        2035     0.005669         0.000835           0.001749
                        2040     0.005535         0.000754           0.001576
                        2045     0.004574         0.000577           0.001226
                        2050     0.003171         0.000369           0.000781

sector
technology                   EAF with scrap
scenario                Year
Competitiveness-Erosion 2030       0.000256
                        2035       0.000556
                        2040       0.000466
                        2045       0.000326
                        2050       0.000187

In [78]:
region_name = "South Korea"

# Filter out NaN values if needed
df_use = arrUse.reset_index()
df_use.columns = ['scenario', 'Year', 'sector', 'subsector', 'technology', 'value']
df_use = df_use[(~df_use['value'].isna()) & (df_use['subsector'] != 'biomass')].copy()

# -----------------------------------------------------------
# 1. XML ROOT: <scenario>
# -----------------------------------------------------------
root = ET.Element("scenario")

# -----------------------------------------------------------
# 2. Add <world> and <region>
# -----------------------------------------------------------
world_el = ET.SubElement(root, "world")

region_el = ET.SubElement(world_el, "region")
region_el.set("name", region_name)

In [79]:
for sector_name in df_use['sector'].unique():
    supplysector_el = ET.SubElement(region_el, "supplysector")
    supplysector_el.set("name", sector_name)

    df_sector = df_use[df_use['sector'] == sector_name]

    for subsector_name in df_sector['subsector'].unique():
        subsector_el = ET.SubElement(supplysector_el, "subsector")
        subsector_el.set("name", subsector_name)

        df_sub = df_sector[df_sector['subsector'] == subsector_name]

        for tech_name in df_sub['technology'].unique():
            tech_el = ET.SubElement(subsector_el, "stub-technology")
            tech_el.set("name", tech_name)

            df_tech = df_sub[df_sub['technology'] == tech_name]

            for _, row in df_tech.iterrows():
                year = int(row['Year'])
                val = float(row['value'])

                period_el = ET.SubElement(tech_el, "period")
                period_el.set("year", str(year))

                # NEW BLOCK:
                non_energy_el = ET.SubElement(period_el, "minicam-non-energy-input")
                non_energy_el.set("name", "IronSteel-CBAM")

                input_cost_el = ET.SubElement(non_energy_el, "input-cost")
                input_cost_el.text = f"{val:.4f}"

In [80]:
# Convert raw to string
rough = ET.tostring(root, encoding="utf-8")

# Pretty formatting
pretty = minidom.parseString(rough).toprettyxml(indent="  ")

# Save
with open("../input/policy/industry/ironsteel_cbam_ERT_Competitiveness_Erosion.xml", "w", encoding="utf-8") as f:
    f.write(pretty)

In [81]:
arrCO2ChemDirect = dfCO2[(dfCO2['sector'].str.contains('chemical')) & (dfCO2['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrCO2ChemDirect

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                 0.453590
                                                                     biomass CCS             0.000901
                                                    coal             coal                    0.081968
                                                                     coal CCS                0.000040
                                                    gas              gas                     0.506547
                                                                     gas CCS                 0.000584
                                                    refined liquids  refined liquids         1.474630
                                                                     refined liquids CCS     0.001499
                               chemical feedstocks  coal             coal                    0.137213
                                                    refined liquids  refined liquids        10.903400
                         2035  chemical energy use  biomass          biomass                 0.443247
                                                                     biomass CCS             0.002353
                                                    coal             coal                    0.074509
                                                                     coal CCS                0.000102
                                                    gas              gas                     0.474195
                                                                     gas CCS                 0.001379
                                                    refined liquids  refined liquids         1.363885
                                                                     refined liquids CCS     0.003443
                               chemical feedstocks  coal             coal                    0.135992
                                                    refined liquids  refined liquids        10.572600
                         2040  chemical energy use  biomass          biomass                 0.409461
                                                                     biomass CCS             0.008666
                                                    coal             coal                    0.054238
                                                                     coal CCS                0.000346
                                                    gas              gas                     0.384334
                                                                     gas CCS                 0.004363
                                                    refined liquids  refined liquids         1.064739
                                                                     refined liquids CCS     0.010830
                               chemical feedstocks  coal             coal                    0.123380
                                                    refined liquids  refined liquids         9.721050
                         2045  chemical energy use  biomass          biomass                 0.346277
                                                                     biomass CCS             0.021170
                                                    coal             coal                    0.028483
                                                                     coal CCS                0.000744
                                                    gas              gas                     0.263971
                                                                     gas CCS                 0.009087
                                                    refined liquids  refined liquids         0.677193
                                                                     refined liquids CCS     0.022381
                               chemical feedstocks  coal             coal                    0.101314
                                                    refined liquids  refined liquids         8.481730
                         2050  chemical energy use  biomass          biomass                 0.273544
                                                                     biomass CCS             0.027547
                                                    coal             coal                    0.014265
                                                                     coal CCS                0.000909
                                                    gas              gas                     0.183168
                                                                     gas CCS                 0.011055
                                                    refined liquids  refined liquids         0.437206
                                                                     refined liquids CCS     0.027034
                               chemical feedstocks  coal             coal                    0.076905
                                                    refined liquids  refined liquids         7.197160
Name: value, dtype: float64

In [82]:
dfInput = run_query(conn=conn, q_idx=100, scenarios=scenario, regions=['South Korea'])
dfInputIndirect = dfInput[(dfInput['sector'].str.contains('chemical')) & (dfInput['Year'] >= 2030)].copy()
df_indirect = (
    dfInputIndirect
    .merge(df_ci, on=["input", "Year"], how="left")
)
df_indirect["indirect_emissions_MtC"] = (
    df_indirect["value"] * df_indirect["ci"]
)
df_indirect
arrCO2ChemIndirect = df_indirect.groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['indirect_emissions_MtC'].sum()
arrCO2ChemIndirect

industry final energy by tech and fuel

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                0.000000
                                                                     biomass CCS            0.000000
                                                    coal             coal                   0.000000
                                                                     coal CCS               0.000000
                                                    electricity      electricity            3.972307
                                                    gas              gas                    0.000000
                                                                     gas CCS                0.000000
                                                    refined liquids  refined liquids        0.000000
                                                                     refined liquids CCS    0.000000
                               chemical feedstocks  coal             coal                   0.000000
                                                    refined liquids  refined liquids        0.000000
                         2035  chemical energy use  biomass          biomass                0.000000
                                                                     biomass CCS            0.000000
                                                    coal             coal                   0.000000
                                                                     coal CCS               0.000000
                                                    electricity      electricity            2.937410
                                                    gas              gas                    0.000000
                                                                     gas CCS                0.000000
                                                    refined liquids  refined liquids        0.000000
                                                                     refined liquids CCS    0.000000
                               chemical feedstocks  coal             coal                   0.000000
                                                    refined liquids  refined liquids        0.000000
                         2040  chemical energy use  biomass          biomass                0.000000
                                                                     biomass CCS            0.000000
                                                    coal             coal                   0.000000
                                                                     coal CCS               0.000000
                                                    electricity      electricity            2.479943
                                                    gas              gas                    0.000000
                                                                     gas CCS                0.000000
                                                    refined liquids  refined liquids        0.000000
                                                                     refined liquids CCS    0.000000
                               chemical feedstocks  coal             coal                   0.000000
                                                    refined liquids  refined liquids        0.000000
                         2045  chemical energy use  biomass          biomass                0.000000
                                                                     biomass CCS            0.000000
                                                    coal             coal                   0.000000
                                                                     coal CCS               0.000000
                                                    electricity      electricity            2.004075
                                                    gas              gas                    0.000000
                                                                     gas CCS                0.000000
                                                    refined liquids  refined liquids        0.000000
                                                                     refined liquids CCS    0.000000
                               chemical feedstocks  coal             coal                   0.000000
                                                    refined liquids  refined liquids        0.000000
                         2050  chemical energy use  biomass          biomass                0.000000
                                                                     biomass CCS            0.000000
                                                    coal             coal                   0.000000
                                                                     coal CCS               0.000000
                                                    electricity      electricity            1.215593
                                                    gas              gas                    0.000000
                                                                     gas CCS                0.000000
                                                    refined liquids  refined liquids        0.000000
                                                                     refined liquids CCS    0.000000
                               chemical feedstocks  coal             coal                   0.000000
                                                    refined liquids  refined liquids        0.000000
Name: indirect_emissions_MtC, dtype: float64

In [83]:
arrCO2Chem = arrCO2ChemIndirect.add(arrCO2ChemDirect, fill_value=0)
arrCO2Chem

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                 0.453590
                                                                     biomass CCS             0.000901
                                                    coal             coal                    0.081968
                                                                     coal CCS                0.000040
                                                    electricity      electricity             3.972307
                                                    gas              gas                     0.506547
                                                                     gas CCS                 0.000584
                                                    refined liquids  refined liquids         1.474630
                                                                     refined liquids CCS     0.001499
                               chemical feedstocks  coal             coal                    0.137213
                                                    refined liquids  refined liquids        10.903400
                         2035  chemical energy use  biomass          biomass                 0.443247
                                                                     biomass CCS             0.002353
                                                    coal             coal                    0.074509
                                                                     coal CCS                0.000102
                                                    electricity      electricity             2.937410
                                                    gas              gas                     0.474195
                                                                     gas CCS                 0.001379
                                                    refined liquids  refined liquids         1.363885
                                                                     refined liquids CCS     0.003443
                               chemical feedstocks  coal             coal                    0.135992
                                                    refined liquids  refined liquids        10.572600
                         2040  chemical energy use  biomass          biomass                 0.409461
                                                                     biomass CCS             0.008666
                                                    coal             coal                    0.054238
                                                                     coal CCS                0.000346
                                                    electricity      electricity             2.479943
                                                    gas              gas                     0.384334
                                                                     gas CCS                 0.004363
                                                    refined liquids  refined liquids         1.064739
                                                                     refined liquids CCS     0.010830
                               chemical feedstocks  coal             coal                    0.123380
                                                    refined liquids  refined liquids         9.721050
                         2045  chemical energy use  biomass          biomass                 0.346277
                                                                     biomass CCS             0.021170
                                                    coal             coal                    0.028483
                                                                     coal CCS                0.000744
                                                    electricity      electricity             2.004075
                                                    gas              gas                     0.263971
                                                                     gas CCS                 0.009087
                                                    refined liquids  refined liquids         0.677193
                                                                     refined liquids CCS     0.022381
                               chemical feedstocks  coal             coal                    0.101314
                                                    refined liquids  refined liquids         8.481730
                         2050  chemical energy use  biomass          biomass                 0.273544
                                                                     biomass CCS             0.027547
                                                    coal             coal                    0.014265
                                                                     coal CCS                0.000909
                                                    electricity      electricity             1.215593
                                                    gas              gas                     0.183168
                                                                     gas CCS                 0.011055
                                                    refined liquids  refined liquids         0.437206
                                                                     refined liquids CCS     0.027034
                               chemical feedstocks  coal             coal                    0.076905
                                                    refined liquids  refined liquids         7.197160
dtype: float64

In [84]:
dfChemTech = run_query(conn=conn, q_idx=100, scenarios=scenario, regions=['South Korea'])
arrChemTech = dfChemTech[(dfChemTech['sector'].str.contains('chemical')) & (dfChemTech['Year'] >= 2030)].groupby(['scenario', 'Year', 'sector', 'subsector', 'technology'])['value'].sum()
arrChemTech

industry final energy by tech and fuel

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                0.019721
                                                                     biomass CCS            0.000392
                                                    coal             coal                   0.003002
                                                                     coal CCS               0.000015
                                                    electricity      electricity            0.216234
                                                    gas              gas                    0.035672
                                                                     gas CCS                0.000411
                                                    refined liquids  refined liquids        0.075237
                                                                     refined liquids CCS    0.000765
                               chemical feedstocks  coal             coal                   0.020105
                                                    refined liquids  refined liquids        2.225180
                         2035  chemical energy use  biomass          biomass                0.019272
                                                                     biomass CCS            0.001023
                                                    coal             coal                   0.002729
                                                                     coal CCS               0.000037
                                                    electricity      electricity            0.222040
                                                    gas              gas                    0.033394
                                                                     gas CCS                0.000971
                                                    refined liquids  refined liquids        0.069586
                                                                     refined liquids CCS    0.001757
                               chemical feedstocks  coal             coal                   0.019926
                                                    refined liquids  refined liquids        2.157670
                         2040  chemical energy use  biomass          biomass                0.017803
                                                                     biomass CCS            0.003768
                                                    coal             coal                   0.001987
                                                                     coal CCS               0.000127
                                                    electricity      electricity            0.247420
                                                    gas              gas                    0.027066
                                                                     gas CCS                0.003073
                                                    refined liquids  refined liquids        0.054323
                                                                     refined liquids CCS    0.005525
                               chemical feedstocks  coal             coal                   0.018078
                                                    refined liquids  refined liquids        1.983890
                         2045  chemical energy use  biomass          biomass                0.015056
                                                                     biomass CCS            0.009204
                                                    coal             coal                   0.001043
                                                                     coal CCS               0.000272
                                                    electricity      electricity            0.281492
                                                    gas              gas                    0.018590
                                                                     gas CCS                0.006399
                                                    refined liquids  refined liquids        0.034551
                                                                     refined liquids CCS    0.011419
                               chemical feedstocks  coal             coal                   0.014845
                                                    refined liquids  refined liquids        1.730960
                         2050  chemical energy use  biomass          biomass                0.011893
                                                                     biomass CCS            0.011977
                                                    coal             coal                   0.000523
                                                                     coal CCS               0.000333
                                                    electricity      electricity            0.277887
                                                    gas              gas                    0.012899
                                                                     gas CCS                0.007785
                                                    refined liquids  refined liquids        0.022306
                                                                     refined liquids CCS    0.013793
                               chemical feedstocks  coal             coal                   0.011268
                                                    refined liquids  refined liquids        1.468810
Name: value, dtype: float64

In [85]:
arrTax = dfTax[(dfTax.index >= 2030)]['D'] # 1990$ / tC
arrTax

Year
2030    118.596775
2035    321.369800
2040    317.819600
2045    265.756500
2050    186.333400
Name: D, dtype: float64

In [86]:
arrCO2I = (arrCO2Chem / arrChemTech) # MTC / EJ
arrCO2I

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                22.999973
                                                                     biomass CCS             2.300000
                                                    coal             coal                   27.300012
                                                                     coal CCS                2.730000
                                                    electricity      electricity            18.370376
                                                    gas              gas                    14.200015
                                                                     gas CCS                 1.419999
                                                    refined liquids  refined liquids        19.599923
                                                                     refined liquids CCS     1.960000
                               chemical feedstocks  coal             coal                    6.824989
                                                    refined liquids  refined liquids         4.900008
                         2035  chemical energy use  biomass          biomass                23.000001
                                                                     biomass CCS             2.300004
                                                    coal             coal                   27.299954
                                                                     coal CCS                2.730000
                                                    electricity      electricity            13.229176
                                                    gas              gas                    14.199990
                                                                     gas CCS                 1.420000
                                                    refined liquids  refined liquids        19.599956
                                                                     refined liquids CCS     1.959999
                               chemical feedstocks  coal             coal                    6.824989
                                                    refined liquids  refined liquids         4.900008
                         2040  chemical energy use  biomass          biomass                23.000052
                                                                     biomass CCS             2.299998
                                                    coal             coal                   27.299940
                                                                     coal CCS                2.729997
                                                    electricity      electricity            10.023203
                                                    gas              gas                    14.200024
                                                                     gas CCS                 1.419999
                                                    refined liquids  refined liquids        19.600005
                                                                     refined liquids CCS     1.960000
                               chemical feedstocks  coal             coal                    6.825021
                                                    refined liquids  refined liquids         4.899994
                         2045  chemical energy use  biomass          biomass                22.999999
                                                                     biomass CCS             2.300003
                                                    coal             coal                   27.299949
                                                                     coal CCS                2.730002
                                                    electricity      electricity             7.119466
                                                    gas              gas                    14.199998
                                                                     gas CCS                 1.419999
                                                    refined liquids  refined liquids        19.600016
                                                                     refined liquids CCS     1.960003
                               chemical feedstocks  coal             coal                    6.825019
                                                    refined liquids  refined liquids         4.900015
                         2050  chemical energy use  biomass          biomass                22.999996
                                                                     biomass CCS             2.299999
                                                    coal             coal                   27.300034
                                                                     coal CCS                2.730003
                                                    electricity      electricity             4.374407
                                                    gas              gas                    14.199995
                                                                     gas CCS                 1.420000
                                                    refined liquids  refined liquids        19.600018
                                                                     refined liquids CCS     1.960003
                               chemical feedstocks  coal             coal                    6.825002
                                                    refined liquids  refined liquids         4.899994
dtype: float64

In [87]:
ALPHA_EU_CHEMICAL = (4.812/159.5)
arrUse = ALPHA_EU_CHEMICAL * arrCO2I * arrTax * CONVERT_1990_TO_1975 / 1000 # (1975$/1990$) * (1990$ / tC) * (MTC / EJ) / 1000 = 1975$ / GJ
arrUse

scenario                 Year  sector               subsector        technology
Competitiveness-Erosion  2030  chemical energy use  biomass          biomass                0.038572
                                                                     biomass CCS            0.003857
                                                    coal             coal                   0.045783
                                                                     coal CCS               0.004578
                                                    electricity      electricity            0.030808
                                                    gas              gas                    0.023814
                                                                     gas CCS                0.002381
                                                    refined liquids  refined liquids        0.032870
                                                                     refined liquids CCS    0.003287
                               chemical feedstocks  coal             coal                   0.011446
                                                    refined liquids  refined liquids        0.008218
                         2035  chemical energy use  biomass          biomass                0.104521
                                                                     biomass CCS            0.010452
                                                    coal             coal                   0.124062
                                                                     coal CCS               0.012406
                                                    electricity      electricity            0.060119
                                                    gas              gas                    0.064530
                                                                     gas CCS                0.006453
                                                    refined liquids  refined liquids        0.089070
                                                                     refined liquids CCS    0.008907
                               chemical feedstocks  coal             coal                   0.031015
                                                    refined liquids  refined liquids        0.022268
                         2040  chemical energy use  biomass          biomass                0.103367
                                                                     biomass CCS            0.010337
                                                    coal             coal                   0.122691
                                                                     coal CCS               0.012269
                                                    electricity      electricity            0.045046
                                                    gas              gas                    0.063818
                                                                     gas CCS                0.006382
                                                    refined liquids  refined liquids        0.088086
                                                                     refined liquids CCS    0.008809
                               chemical feedstocks  coal             coal                   0.030673
                                                    refined liquids  refined liquids        0.022022
                         2045  chemical energy use  biomass          biomass                0.086434
                                                                     biomass CCS            0.008643
                                                    coal             coal                   0.102593
                                                                     coal CCS               0.010259
                                                    electricity      electricity            0.026755
                                                    gas              gas                    0.053363
                                                                     gas CCS                0.005336
                                                    refined liquids  refined liquids        0.073657
                                                                     refined liquids CCS    0.007366
                               chemical feedstocks  coal             coal                   0.025648
                                                    refined liquids  refined liquids        0.018414
                         2050  chemical energy use  biomass          biomass                0.060602
                                                                     biomass CCS            0.006060
                                                    coal             coal                   0.071932
                                                                     coal CCS               0.007193
                                                    electricity      electricity            0.011526
                                                    gas              gas                    0.037415
                                                                     gas CCS                0.003742
                                                    refined liquids  refined liquids        0.051644
                                                                     refined liquids CCS    0.005164
                               chemical feedstocks  coal             coal                   0.017983
                                                    refined liquids  refined liquids        0.012911
dtype: float64

In [88]:
df_use = arrUse.reset_index()
df_use.columns

Index(['scenario', 'Year', 'sector', 'subsector', 'technology', 0], dtype='object')

In [89]:
df_use['scenario'] = scenario[0]
df_use.pivot(index=['scenario', 'Year'], columns=['sector', 'technology'], values=0)

sector                       chemical energy use                        \
technology                               biomass biomass CCS      coal
scenario                Year
Competitiveness-Erosion 2030            0.038572    0.003857  0.045783
                        2035            0.104521    0.010452  0.124062
                        2040            0.103367    0.010337  0.122691
                        2045            0.086434    0.008643  0.102593
                        2050            0.060602    0.006060  0.071932

sector                                                                  \
technology                    coal CCS electricity       gas   gas CCS
scenario                Year
Competitiveness-Erosion 2030  0.004578    0.030808  0.023814  0.002381
                        2035  0.012406    0.060119  0.064530  0.006453
                        2040  0.012269    0.045046  0.063818  0.006382
                        2045  0.010259    0.026755  0.053363  0.005336
                        2050  0.007193    0.011526  0.037415  0.003742

sector                                                            \
technology                   refined liquids refined liquids CCS
scenario                Year
Competitiveness-Erosion 2030        0.032870            0.003287
                        2035        0.089070            0.008907
                        2040        0.088086            0.008809
                        2045        0.073657            0.007366
                        2050        0.051644            0.005164

sector                       chemical feedstocks
technology                                  coal refined liquids
scenario                Year
Competitiveness-Erosion 2030            0.011446        0.008218
                        2035            0.031015        0.022268
                        2040            0.030673        0.022022
                        2045            0.025648        0.018414
                        2050            0.017983        0.012911

In [90]:
region_name = "South Korea"

# Filter out NaN values if needed
df_use = arrUse.reset_index()
df_use.columns = ['scenario', 'Year', 'sector', 'subsector', 'technology', 'value']
df_use = df_use[(~df_use['value'].isna()) & (df_use['subsector'] != 'biomass')].copy()

# -----------------------------------------------------------
# 1. XML ROOT: <scenario>
# -----------------------------------------------------------
root = ET.Element("scenario")

# -----------------------------------------------------------
# 2. Add <world> and <region>
# -----------------------------------------------------------
world_el = ET.SubElement(root, "world")

region_el = ET.SubElement(world_el, "region")
region_el.set("name", region_name)

In [91]:
for sector_name in df_use['sector'].unique():
    supplysector_el = ET.SubElement(region_el, "supplysector")
    supplysector_el.set("name", sector_name)

    df_sector = df_use[df_use['sector'] == sector_name]

    for subsector_name in df_sector['subsector'].unique():
        subsector_el = ET.SubElement(supplysector_el, "subsector")
        subsector_el.set("name", subsector_name)

        df_sub = df_sector[df_sector['subsector'] == subsector_name]

        for tech_name in df_sub['technology'].unique():
            tech_el = ET.SubElement(subsector_el, "stub-technology")
            tech_el.set("name", tech_name)

            df_tech = df_sub[df_sub['technology'] == tech_name]

            for _, row in df_tech.iterrows():
                year = int(row['Year'])
                val = float(row['value'])

                period_el = ET.SubElement(tech_el, "period")
                period_el.set("year", str(year))

                # NEW BLOCK:
                non_energy_el = ET.SubElement(period_el, "minicam-non-energy-input")
                non_energy_el.set("name", "Chemical-CBAM")

                input_cost_el = ET.SubElement(non_energy_el, "input-cost")
                input_cost_el.text = f"{val:.4f}"

In [92]:
# Convert raw to string
rough = ET.tostring(root, encoding="utf-8")

# Pretty formatting
pretty = minidom.parseString(rough).toprettyxml(indent="  ")

# Save
with open("../input/policy/industry/chemical_cbam_ERT_Competitiveness_Erosion.xml", "w", encoding="utf-8") as f:
    f.write(pretty)