In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("./extdata/HOME_발전설비_발전기세부내역.csv", encoding='cp949')
df.head()

,발전원,발전소명,단위용량,대수,용량,준공,형식,연료,보일러(NSSS)\n제작사,터빈(수차)\n제작사,발전기 제작사,발전회사,정격전압,용도별,회원,시장,급전,소재지 및\n주요생산품목(상용자가)
0,기력,강릉안인#1,1040000,1,1040000.0,2022.10,기력,유연탄,두산중공업,두산중공업,두산중공업,강릉에코파워㈜,30kV,사업용,정회원,시장,중앙,강원도 강릉시 강동면
1,기력,강릉안인#2,1040000,1,1040000.0,2022.10,기력,유연탄,두산중공업,두산중공업,두산중공업,강릉에코파워㈜,30kV,사업용,정회원,시장,중앙,강원도 강릉시 강동면
2,기력,고성#1,1040000,1,1040000.0,2021.5,기력,유연탄,두산중공업,두산중공업,두산중공업,고성그린파워㈜,30kV,사업용,정회원,시장,중앙,경남 고성군 하이면
3,기력,고성#2,1040000,1,1040000.0,2021.10,기력,유연탄,두산중공업,두산중공업,두산중공업,고성그린파워㈜,30kV,사업용,정회원,시장,중앙,경남 고성군 하이면
4,기력,남제주#1,100000,1,100000.0,2006.9,신재생,바이오중유,두산중공업,Mitsubish,Mitsubish,남부발전㈜,13.8kV,사업용,정회원,시장,중앙,제주 서귀포시 안덕면

In [6]:
df['company'] = (
    df['발전회사']
      .str.replace(r'\s*(\(|（)?(주|유)(\)|）)?\s*', '', regex=True)
      .str.replace(r'㈜', '', regex=True)
      .str.strip()
)

In [7]:
df.head()

,발전원,발전소명,단위용량,대수,용량,준공,형식,연료,보일러(NSSS)\n제작사,터빈(수차)\n제작사,발전기 제작사,발전회사,정격전압,용도별,회원,시장,급전,소재지 및\n주요생산품목(상용자가),company
0,기력,강릉안인#1,1040000,1,1040000.0,2022.10,기력,유연탄,두산중공업,두산중공업,두산중공업,강릉에코파워㈜,30kV,사업용,정회원,시장,중앙,강원도 강릉시 강동면,강릉에코파워
1,기력,강릉안인#2,1040000,1,1040000.0,2022.10,기력,유연탄,두산중공업,두산중공업,두산중공업,강릉에코파워㈜,30kV,사업용,정회원,시장,중앙,강원도 강릉시 강동면,강릉에코파워
2,기력,고성#1,1040000,1,1040000.0,2021.5,기력,유연탄,두산중공업,두산중공업,두산중공업,고성그린파워㈜,30kV,사업용,정회원,시장,중앙,경남 고성군 하이면,고성그린파워
3,기력,고성#2,1040000,1,1040000.0,2021.10,기력,유연탄,두산중공업,두산중공업,두산중공업,고성그린파워㈜,30kV,사업용,정회원,시장,중앙,경남 고성군 하이면,고성그린파워
4,기력,남제주#1,100000,1,100000.0,2006.9,신재생,바이오중유,두산중공업,Mitsubish,Mitsubish,남부발전㈜,13.8kV,사업용,정회원,시장,중앙,제주 서귀포시 안덕면,남부발전

In [21]:
df['연료'].unique()

array(['유연탄', '바이오중유', '무연탄', '바이오', '중유', 'LNG', '경유', 'LSWR', '소수력',
       '수력', '해양 에너지', '양수', '농축U', '천연U', '역청탄', '유연탄*', 'LPG*'],
      dtype=object)

In [8]:
df['company'].unique()

array(['강릉에코파워', '고성그린파워', '남부발전', '동서발전', '중부발전', 'GS 동해전력', '남동발전',
       '서부발전', '한국전력', 'SK E&S', 'GS EPS', '씨지앤대산 전력', '동두천드림파워',
       '부산정관 에너지', '신평택 발전', '에스파워', '여에너지서비스', '코스포 영남파워', '평택에너지서비스',
       '씨지앤율촌 전력', '파에너지서비스', '포스코 에너지', '포천파워', '포천민자발전', 'KC하이드로',
       '농어촌공사', '한수원', '수자원공사', '산청군', '경천', '신에너지', '-', '극동소수력',
       '극동제2소수력발전소', '크린에너지', '서울시상하수도', 'GS 파워', '청풍에너지', '대한수력발전',
       '희도전력', 'GS', '산내소수력 발전소', '인제군청', '성발전', '한여울', '애플에너지', '제도청',
       '함양군청', '포스코', '대동기업', '정선소수력', '탑정', '한국해양과학기술원', '한석에너지',
       '홍익이앤알', '에스지씨 에너지 군산사업부문', '지역난방공사', 'GS E&R', '금호석화학',
       '김천에너지서비스', '내포그린에너지', '서울에너지공사', '미래엔 인천에너지', '대구그린 파워',
       '지역난방 공사', '대구염색산업단지관리공단', '토지택공사', '대전열병합 발전', '데이원에너지', '디에스파워',
       '무림파워텍', '별내에너지', '부산패션칼라산업협동조합', 'GS파워', '상공에너지', 'OCI SE',
       '인천종합 에너지', '수완에너지', '안산 도시개발', '대륜발전', '위례에너지서비스', '인천공항 에너지',
       '전북집단 에너지', '춘천에너지', '지에스포천그린에너지', '나래에너지 서비스'], dtype=object)

In [19]:
df['대수'].unique()

array([1, 2, 3, 4, 6, 0])

In [10]:
df[(df['단위용량'] >= 500000)]['company'].unique()

array(['강릉에코파워', '고성그린파워', '동서발전', '중부발전', 'GS 동해전력', '남부발전', '남동발전',
       '서부발전', '한수원'], dtype=object)

In [22]:
listFF = [
    '유연탄', '바이오중유', '무연탄', '중유', 'LNG', '경유', 'LSWR',
    '농축U', '천연U', '역청탄', '유연탄*', 'LPG*'
]

In [28]:
dfComp = df[(df['연료'].isin(listFF))].groupby(['company'])['용량'].sum().reset_index()
dfComp[(dfComp['용량'] >= 500000)]['company'].nunique()

25

In [36]:
dfComp[(dfComp['용량'] >= 500000)]['용량'].sum() / dfComp['용량'].sum()

0.9482260433369913

In [32]:
capatotal2024kw = 152768303
gentotal2024mwh = 627784214
av_cap_fac = gentotal2024mwh / (capatotal2024kw * 8.760)
av_cap_fac

0.4691082063788595

In [34]:
105806705.0 * 8760 * av_cap_fac / 1e9 * 0.14

60.87211087767128

In [35]:
rec_demand = 63307000
rec_demand / gentotal2024mwh

0.10084197497836414

In [ ]:
105806705.0 * 8760 * av_cap_fac / 1e9 * 0.14

In [16]:
df['company'].unique()

array(['강릉에코파워', '고성그린파워', '남부발전', '동서발전', '중부발전', 'GS 동해전력', '남동발전',
       '서부발전', '한국전력', 'SK E&S', 'GS EPS', '씨지앤대산 전력', '동두천드림파워',
       '부산정관 에너지', '신평택 발전', '에스파워', '여에너지서비스', '코스포 영남파워', '평택에너지서비스',
       '씨지앤율촌 전력', '파에너지서비스', '포스코 에너지', '포천파워', '포천민자발전', 'KC하이드로',
       '농어촌공사', '한수원', '수자원공사', '산청군', '경천', '신에너지', '-', '극동소수력',
       '극동제2소수력발전소', '크린에너지', '서울시상하수도', 'GS 파워', '청풍에너지', '대한수력발전',
       '희도전력', 'GS', '산내소수력 발전소', '인제군청', '성발전', '한여울', '애플에너지', '제도청',
       '함양군청', '포스코', '대동기업', '정선소수력', '탑정', '한국해양과학기술원', '한석에너지',
       '홍익이앤알', '에스지씨 에너지 군산사업부문', '지역난방공사', 'GS E&R', '금호석화학',
       '김천에너지서비스', '내포그린에너지', '서울에너지공사', '미래엔 인천에너지', '대구그린 파워',
       '지역난방 공사', '대구염색산업단지관리공단', '토지택공사', '대전열병합 발전', '데이원에너지', '디에스파워',
       '무림파워텍', '별내에너지', '부산패션칼라산업협동조합', 'GS파워', '상공에너지', 'OCI SE',
       '인천종합 에너지', '수완에너지', '안산 도시개발', '대륜발전', '위례에너지서비스', '인천공항 에너지',
       '전북집단 에너지', '춘천에너지', '지에스포천그린에너지', '나래에너지 서비스'], dtype=object)