In [1]:
import gcamreader
import pandas as pd
import os
from pathlib import Path
import numpy as np
from pathlib import Path
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import plotly.express as px
import matplotlib.pyplot as plt

In [2]:
# =========================================================
# Config
# =========================================================
PROJECT_PATH   = Path("../")
DB_REL_PATH    = PROJECT_PATH / "output"
DB_FILE        = "database_basexdb_korea_2035_v5"
QUERY_FILE     = DB_REL_PATH / "queries" / "Main_queries.xml"

REGION = ['South Korea']

In [3]:
# =========================================================
# DB helpers
# =========================================================
def connect_db():
    return gcamreader.LocalDBConn(DB_REL_PATH, DB_FILE)

def check_query_idx():
    queries = gcamreader.parse_batch_query(os.fspath(QUERY_FILE))
    for i, q in enumerate(queries):
        print(i, q.title)

def run_query(conn, q_idx, scenarios, regions=None):
    queries = gcamreader.parse_batch_query(os.fspath(QUERY_FILE))
    q = queries[q_idx]
    print(q.title)
    df = conn.runQuery(q, scenarios=scenarios, regions=regions)
    df["scenario"] = df["scenario"].str.split(",").str[0]
    return df

def get_scenario_name(conn):
    scenarios = list(conn.listScenariosInDB()['name'].unique())
    return scenarios

In [4]:
def convert_to_mt(row):
    val, unit = row['value'], row['Units']
    if unit == 'Tg':
        return val
    elif unit == 'Gg':
        return val * 1e-3
    elif unit == 'MTC':
        return val * (44.009 / 12.011)
    else:
        raise ValueError(f"Unknown unit: {unit}")

# AR5 100‑yr GWP (no climate–carbon feedbacks)
GWP_AR5 = {
    'CO2':      1,      
    'CH4':     28,      
    'CH4_AGR': 28,
    'CH4_AWB': 28,
    'N2O':    265,      
    'N2O_AGR':265,
    'N2O_AWB':265,
    'HFC125': 3170,     
    'HFC134a':1300,     
    'HFC143a':4800,     
    'HFC23': 12400,     
    'HFC32':   677,     
    'HFC43':  1650,     
    'HFC227ea':3350,    
    'HFC236fa':8060,    
    'SF6':   23500,     
    'C2F6':  11100,     
    'CF4':    6630,     
}

In [5]:
check_query_idx()

0 primary energy consumption by region (avg fossil efficiency)
1 primary energy consumption by region (direct equivalent)
2 primary energy consumption with CCS by region (direct equivalent)
3 resource production
4 resource production by tech and vintage
5 resource supply curves
6 regional primary energy prices
7 elec gen by region (incl CHP)
8 elec gen by subsector
9 elec gen by gen tech
10 elec gen by gen tech and cooling tech
11 elec gen by gen tech and cooling tech and vintage
12 elec gen by gen tech and cooling tech (new)
13 elec energy input by subsector
14 elec energy input by elec gen tech
15 elec energy input by elec gen tech and cooling tech
16 elec prices by sector
17 elec gen costs by subsector
18 elec gen costs by tech
19 elec gen costs by cooling tech
20 elec share-weights by subsector
21 elec share-weights by tech
22 elec share-weights by cooling tech
23 elec td inputs and outputs
24 cogeneration by region
25 elec consumption by demand sector
26 elec sector water withdrawals
27 elec sector water consumption
28 elec water withdrawals by gen tech
29 elec water consumption by gen tech
30 elec water withdrawals by gen tech and cooling tech
31 elec water consumption by gen tech and cooling tech
32 elec water withdrawals by gen tech and cooling tech (new)
33 elec water consumption by gen tech and cooling tech (new)
34 refined liquids production by region
35 refined liquids production by subsector
36 refined liquids production by tech
37 refined liquids production by tech and vintage
38 refined liquids production by tech (new)
39 refinery inputs by tech (energy and feedstocks)
40 refined liquids prices by sector
41 refined liquids costs by subsector
42 refined liquids costs by tech
43 refining and oil share-weights by subsector
44 refining share-weights by tech
45 hydrogen production by tech
46 hydrogen inputs by tech
47 hydrogen prices by sector
48 hydrogen costs by tech
49 hydrogen technology IO coefficients
50 hydrogen utilization by technology
51 hydrogen non-energy costs
52 hydrogen outputs by technology
53 hydrogen dispensing energy by primary fuel
54 gas production by tech
55 gas production share-weights by subsector
56 gas inputs by tech (energy and feedstocks)
57 gas pipeline inputs and outputs
58 gas prices by sector
59 gas costs by tech
60 gas consumption by sector
61 delivered gas energy by primary fuel
62 district heat production by subsector (fuel)
63 district heat energy inputs by subsector
64 total final energy by region
65 total final energy by aggregate sector
66 total final energy by sector
67 final energy consumption by fuel
68 final energy consumption by sector and fuel
69 final energy prices
70 building floorspace
71 building floorspace per capita
72 building commercial floorspace satiation impedance
73 building residential floorspace regional bias adder
74 building total final energy by region
75 building total final energy by service
76 building final energy by fuel
77 building final energy by service and fuel
78 building final energy by subsector
79 building final energy by tech
80 building final energy by tech and vintage
81 building final energy by tech (new)
82 building service output by service
83 building service output by subsector
84 building service output by tech
85 building service output by tech and vintage
86 building service output by tech (new)
87 building service density by energy service
88 building satiation impedance by energy service
89 building regional bias adder by energy service
90 building internal gain energy by service
91 total service cost per unit floorspace
92 building service costs
93 fuel prices to buildings
94 building share-weights by subsector
95 building share-weights by tech
96 industry total final energy by region
97 industry total final energy by service
98 industry final energy by fuel
99 industry final energy by service and fuel
100 industry final energy by tech and fuel
101 industry feedstocks by type
102 industry primary output by sector
103 industry cogeneration by fuel
104 fuel prices to industry
105 industry share-weights by subsector
106 industry water withdrawals and consumption
107 cement production by region
108 cement production by tech (conv and ccs)
109 cement production by tech and vintage
110 inputs to cement production
111 cement prices
112 ammonia production by region
113 ammonia production by tech
114 ammonia inputs by tech (energy and feedstocks)
115 ammonia and N fertilizer prices
116 ammonia domestic supply
117 ammonia exports (query USA region)
118 iron and steel production by region
119 iron and steel production by tech
120 iron and steel production by tech and vintage
121 iron and steel inputs by tech (energy and feedstocks)
122 iron and steel prices
123 traded iron and steel
124 regional iron and steel sources
125 chemical production by region
126 chemical inputs by tech (energy and feedstocks)
127 chemical prices
128 aluminum production by region
129 aluminum production by tech
130 aluminum production by tech and vintage
131 aluminum inputs by tech (energy and feedstocks)
132 aluminum prices
133 construction inputs (energy and feedstocks)
134 agricultural energy use
135 mining energy use
136 food processing production by region
137 food processing process heat production by tech
138 inputs to food processing
139 inputs to food processing (process heat separated)
140 food processing prices
141 paper production by region
142 inputs to paper production
143 paper prices
144 energy-for-water TFE
145 energy-for-water FE by fuel
146 energy-for-water FE by process and fuel
147 prices of energy-for-water processes
148 water flow volumes of EFW processes
149 nonrenewable groundwater pumping energy
150 transport total final energy by region
151 transport total final energy by service
152 transport final energy by fuel
153 transport final energy by mode and fuel
154 transport final energy by tech and fuel
155 transport final energy by tech and vintage
156 transport final energy by tech (new)
157 transport service output by service
158 transport service output by mode
159 transport service output by tech
160 transport service output by tech and vintage
161 transport service output by tech (new)
162 transport load factors
163 fuel prices to transport
164 costs of transport services
165 costs of transport modes
166 costs of transport techs
167 transport tech non-energy cost
168 LDV energy by primary fuel
169 transport subsector share-weights
170 transport tech share-weights
171 transport speeds
172 building final energy by tech
173 building service output by tech
174 building floorspace
175 industry final energy by service and fuel
176 transport final energy by tech and fuel
177 transport final energy by tech (new)
178 transport service output by tech
179 transport service output by tech (new)
180 detailed land allocation
181 detailed historical land allocation
182 land allocation by crop
183 aggregated land allocation
184 aggregated historical land allocation
185 land allocation in a specified land use region
186 land allocation by crop and water source
187 LUC emissions by region
188 LUC emissions by LUT
189 LUC emissions by LUT in a specified land use region
190 vegetative carbon stock by region
191 profit rate
192 profit rate in a specified land use region
193 land leaf shares
194 land leaf shares in a specified land use region
195 ag production by crop type
196 ag production by subsector (land use region)
197 ag production in a specified land use region
198 ag production by tech
199 ag tech variable cost
200 ag tech yield
201 ag tech yield in a specified land region
202 ag commodity prices
203 ag tech implied subsidy
204 irrigation water withdrawals by region
205 irrigation water withdrawals by crop type
206 irrigation water withdrawals by crop type and land region
207 irrigation water withdrawals by ag tech
208 irrigation water consumption by region
209 irrigation water consumption by crop type
210 irrigation water consumption by crop type and land region
211 irrigation water consumption by ag tech
212 biophysical water demand by region
213 biophysical water demand by crop type
214 biophysical water demand by crop type and land region
215 biophysical water demand by ag tech
216 fertilizer consumption by region
217 fertilizer consumption by crop type
218 fertilizer consumption by ag tech
219 fertilizer-crop input-output coefficients
220 purpose-grown biomass production
221 residue biomass production
222 MSW production
223 regional biomass consumption
224 meat and dairy production by type
225 meat and dairy production by tech
226 meat and dairy prices
227 meat and dairy subsector share-weights
228 meat and dairy tech share-weights
229 meat and dairy subsector costs
230 meat and dairy tech costs
231 water consumption by meat and dairy production
232 feed consumption by region
233 feed consumption by meat and dairy tech
234 feed sources
235 feed prices
236 feed subsector share-weights
237 food consumption by type (general)
238 food consumption by type (specific)
239 demand balances by crop commodity
240 demand balances by meat and dairy commodity
241 food demand prices
242 food demand
243 food demand per capita
244 food demand regional bias
245 ag import vs. domestic supply (Regional Armington competition)
246 ag export to the world center (USA) (Intl. Armington competition)
247 ag import vs. domestic prices
248 ag export prices (at world center USA)
249 import vs. domestic share-weights (Armington regional taste)
250 international competition share-weights (Armington intl. taste)
251 ag total prices (weighted average b/t domestic and imported prices)
252 opening stocks (supply from carryover)
253 closing stocks (before loss/adjustments)
254 closing stocks (after loss/adjustments; carried over)
255 current supply (current or regional consumption)
256 ag regional prices (current consumer prices)
257 agricultural storage share-weights
258 storage cost
259 expected price
260 CO2 emissions by region
261 CO2 emissions by sector (excluding resource production)
262 CO2 emissions by sector (no bio) (excluding resource production)
263 CO2 emissions by assigned sector (no bio) (excluding resource production)
264 CO2 emissions by subsector (excluding resource production)
265 CO2 emissions by tech (excluding resource production)
266 CO2 emissions by resource production
267 CO2 sequestration by sector
268 CO2 sequestration by tech
269 nonCO2 emissions by region
270 nonCO2 emissions by sector (excluding resource production)
271 nonCO2 emissions by resource production
272 nonCO2 emissions by subsector (excluding resource production)
273 nonCO2 emissions by tech (excluding resource production)
274 specific nonCO2 emissions by region
275 specific nonCO2 emissions by sector (excluding resource production)
276 specific nonCO2 emissions by resource production
277 specific nonCO2 emissions by subsector (excluding resource production)
278 specific nonCO2 emissions by tech (excluding resource production)
279 CO2 concentrations
280 total climate forcing
281 global mean temperature
282 net terrestrial C uptake
283 population by region
284 GDP MER by region
285 GDP per capita MER by region
286 GDP per capita PPP by region
287 subregional population
288 subregional income
289 National Account
290 Social Accounting Matrix
291 Tracking accounts by tech
292 Capital investment demands by tech
293 Capital investment demands by resource
294 CO2 prices
295 policy cost by period
296 undiscounted policy cost
297 discounted policy cost
298 regional CO2 MAC curves by period
299 water withdrawals by region
300 water withdrawals by water mapping source
301 water withdrawals by sector
302 water withdrawals by subsector
303 water withdrawals by tech
304 water consumption by region
305 water consumption by water mapping source
306 water consumption by sector
307 water consumption by subsector
308 water consumption by tech
309 Basin level available runoff
310 Water withdrawals by water source (runoff vs. groundwater)
311 Water Withdrawals by Basin (Runoff)
312 Water Withdrawals by Basin (Groundwater)
313 Cumulative groundwater extraction
314 prices of all markets
315 supply of all markets
316 demand of all markets
317 price of a specific market
318 supply of a specific market
319 prices by sector
320 costs by subsector
321 costs by tech
322 costs by tech and input
323 inputs by sector
324 inputs by subsector
325 inputs by tech
326 outputs by sector
327 outputs by subsector
328 outputs by tech
329 input-output coefficients by tech
330 primary energy consumption by region (direct equivalent)
331 industry water withdrawals and consumption
332 elec gen by region (no CHP)
333 elec gen by subsector
334 elec gen by gen tech (cogen only)
335 elec gen by gen tech and cooling tech (incl cogen)
336 elec energy input by subsector
337 elec energy input by elec gen tech
338 elec prices by sector
339 elec gen costs by subsector
340 elec gen costs by tech
341 elec share-weights by subsector
342 elec share-weights by gen tech
343 elec share-weights by cooling tech
344 elec water withdrawals by gen tech and cooling tech
345 elec water consumption by gen tech and cooling tech
346 refined liquids production by region
347 refined liquids production by subsector
348 refined liquids production by tech
349 refined liquids production by tech and vintage
350 refined liquids production by tech (new)
351 refinery inputs by tech (energy and feedstocks)
352 refined liquids prices by sector
353 refined liquids costs by subsector
354 refined liquids costs by tech
355 refining and oil share-weights by subsector
356 refining share-weights by tech
357 total final energy by aggregate sector
358 water withdrawals by state, sector, basin
359 water withdrawals by state, sector, basin (includes desal)
360 water consumption by state, sector, basin
361 water consumption by state, sector, basin (includes desal)
362 CO2 emissions by tech (nested subsector) (excluding resource production)
363 CO2 sequestration by tech (nested subsector)

In [6]:
conn = connect_db()
get_scenario_name(conn)

Database scenarios: High-Ambition-Med, Current-Policies-Med, High-Ambition-Med, Current-Policies-Med, High-Ambition-High, Current-Policies-High, High-Ambition-Med, Current-Policies-Med, Current-Policies-High, High-Ambition-Low, Current-Policies-Low, High-Ambition-Med-AI, Current-Policies-Med-AI, High-Ambition-Med-CPO2040

['High-Ambition-Med',
 'Current-Policies-Med',
 'High-Ambition-High',
 'Current-Policies-High',
 'High-Ambition-Low',
 'Current-Policies-Low',
 'High-Ambition-Med-AI',
 'Current-Policies-Med-AI',
 'High-Ambition-Med-CPO2040']

In [7]:
scenarios = [
    'High-Ambition-Med',
    'Current-Policies-Med',
    'High-Ambition-High',
    'Current-Policies-High',
    'High-Ambition-Low',
    'Current-Policies-Low',
    'High-Ambition-Med-AI',
    'Current-Policies-Med-AI',
    'High-Ambition-Med-CPO2040'
]

In [8]:
df = run_query(conn=conn, q_idx=267, scenarios=scenarios, regions=['South Korea'])
df['sector'].unique()

CO2 sequestration by sector

array(['CO2 removal', 'H2 central production', 'ammonia', 'cement',
       'chemical energy use', 'chemical feedstocks',
       'construction feedstocks', 'elec_coal (IGCC CCS)',
       'elec_coal (conv pul CCS)', 'elec_gas (CC CCS)', 'iron and steel',
       'other industrial feedstocks', 'process heat dac', 'refining',
       'waste biomass for paper'], dtype=object)

In [11]:
df[(df['sector'].isin([
    'H2 central production', 'ammonia', 'cement',
    'chemical energy use', 'elec_coal (IGCC CCS)',
    'elec_coal (conv pul CCS)', 'elec_gas (CC CCS)',
    'iron and steel', 'process heat dac',
    'refining', 'waste biomass for paper'
]))].groupby(['Year', 'scenario'])['value'].sum() * 3.66667

Year  scenario
2020  Current-Policies-High         0.173671
      Current-Policies-Low          0.173671
      Current-Policies-Med          0.173671
      Current-Policies-Med-AI       0.173671
      High-Ambition-High            0.173671
      High-Ambition-Low             0.173671
      High-Ambition-Med             0.173671
      High-Ambition-Med-AI          0.173671
      High-Ambition-Med-CPO2040     0.173671
2025  Current-Policies-High         3.870181
      Current-Policies-Low          3.870181
      Current-Policies-Med          3.870181
      Current-Policies-Med-AI       3.870181
      High-Ambition-High            3.870181
      High-Ambition-Low             3.870181
      High-Ambition-Med             3.870181
      High-Ambition-Med-AI          3.870181
      High-Ambition-Med-CPO2040     3.870181
2030  Current-Policies-High         6.185568
      Current-Policies-Low          6.147891
      Current-Policies-Med          6.097034
      Current-Policies-Med-AI       6.035829
      High-Ambition-High           11.933907
      High-Ambition-Low            10.540058
      High-Ambition-Med            11.728392
      High-Ambition-Med-AI         11.437601
      High-Ambition-Med-CPO2040    11.704697
2035  Current-Policies-High         7.721893
      Current-Policies-Low          7.267332
      Current-Policies-Med          7.344200
      Current-Policies-Med-AI       7.268296
      High-Ambition-High           21.723471
      High-Ambition-Low            18.163324
      High-Ambition-Med            21.097508
      High-Ambition-Med-AI         21.001831
      High-Ambition-Med-CPO2040    21.085423
Name: value, dtype: float64

In [15]:
10.89950 / 9.88319 * 100

110.28321827264274

In [ ]:
12.96070 / 9.88319 * 100

131.13883270482503

In [19]:
14.17780 / 12.96070 * 100

109.39069649015872

In [11]:
df = run_query(conn=conn, q_idx=9, scenarios=scenarios, regions=['South Korea'])
df.groupby(['Year', 'scenario'])['value'].sum() * 277.8

elec gen by gen tech

Year  scenario
1990  Current-Policies-Med        99.491837
      Current-Policies-Med-AI     99.491837
      High-Ambition-Med           99.491837
      High-Ambition-Med-AI        99.491837
2005  Current-Policies-Med       364.976728
      Current-Policies-Med-AI    364.976728
      High-Ambition-Med          364.976728
      High-Ambition-Med-AI       364.976728
2010  Current-Policies-Med       471.223156
      Current-Policies-Med-AI    471.223156
      High-Ambition-Med          471.223156
      High-Ambition-Med-AI       471.223156
2015  Current-Policies-Med       521.782489
      Current-Policies-Med-AI    521.782489
      High-Ambition-Med          521.782489
      High-Ambition-Med-AI       521.782489
2020  Current-Policies-Med       537.796703
      Current-Policies-Med-AI    537.796703
      High-Ambition-Med          537.796703
      High-Ambition-Med-AI       537.796703
2025  Current-Policies-Med       593.276970
      Current-Policies-Med-AI    593.276970
      High-Ambition-Med          593.276970
      High-Ambition-Med-AI       593.276970
2030  Current-Policies-Med       656.896713
      Current-Policies-Med-AI    675.501416
      High-Ambition-Med          690.252893
      High-Ambition-Med-AI       705.656550
2035  Current-Policies-Med       692.327412
      Current-Policies-Med-AI    711.789904
      High-Ambition-Med          786.805271
      High-Ambition-Med-AI       800.498031
Name: value, dtype: float64

In [27]:
df[(df['sector'].str.contains('resid')) & (df['technology'] == 'gas') & (df['Year'] >= 2015) & (df['Year'] ==2030)]

,Units,scenario,region,sector,subsector,Year,technology,value
426,None Specified,Other-CP,South Korea,resid cooling modern_d1,gas,2030,gas,1.0
494,None Specified,Other-CP,South Korea,resid cooling modern_d10,gas,2030,gas,1.0
562,None Specified,Other-CP,South Korea,resid cooling modern_d2,gas,2030,gas,1.0
630,None Specified,Other-CP,South Korea,resid cooling modern_d3,gas,2030,gas,1.0
698,None Specified,Other-CP,South Korea,resid cooling modern_d4,gas,2030,gas,1.0
766,None Specified,Other-CP,South Korea,resid cooling modern_d5,gas,2030,gas,1.0
834,None Specified,Other-CP,South Korea,resid cooling modern_d6,gas,2030,gas,1.0
902,None Specified,Other-CP,South Korea,resid cooling modern_d7,gas,2030,gas,1.0
970,None Specified,Other-CP,South Korea,resid cooling modern_d8,gas,2030,gas,1.0
1038,None Specified,Other-CP,South Korea,resid cooling modern_d9,gas,2030,gas,1.0
1556,None Specified,Other-CP,South Korea,resid heating modern_d1,gas,2030,gas,1.0
1693,None Specified,Other-CP,South Korea,resid heating modern_d10,gas,2030,gas,1.0
1830,None Specified,Other-CP,South Korea,resid heating modern_d2,gas,2030,gas,1.0
1967,None Specified,Other-CP,South Korea,resid heating modern_d3,gas,2030,gas,1.0
2104,None Specified,Other-CP,South Korea,resid heating modern_d4,gas,2030,gas,1.0
2241,None Specified,Other-CP,South Korea,resid heating modern_d5,gas,2030,gas,1.0
2378,None Specified,Other-CP,South Korea,resid heating modern_d6,gas,2030,gas,1.0
2515,None Specified,Other-CP,South Korea,resid heating modern_d7,gas,2030,gas,1.0
2652,None Specified,Other-CP,South Korea,resid heating modern_d8,gas,2030,gas,1.0
2789,None Specified,Other-CP,South Korea,resid heating modern_d9,gas,2030,gas,1.0
3356,None Specified,Other-CP,South Korea,resid others modern_d1,gas,2030,gas,1.0
3493,None Specified,Other-CP,South Korea,resid others modern_d10,gas,2030,gas,1.0
3630,None Specified,Other-CP,South Korea,resid others modern_d2,gas,2030,gas,1.0
3767,None Specified,Other-CP,South Korea,resid others modern_d3,gas,2030,gas,1.0
3904,None Specified,Other-CP,South Korea,resid others modern_d4,gas,2030,gas,1.0
4041,None Specified,Other-CP,South Korea,resid others modern_d5,gas,2030,gas,1.0
4178,None Specified,Other-CP,South Korea,resid others modern_d6,gas,2030,gas,1.0
4315,None Specified,Other-CP,South Korea,resid others modern_d7,gas,2030,gas,1.0
4452,None Specified,Other-CP,South Korea,resid others modern_d8,gas,2030,gas,1.0
4589,None Specified,Other-CP,South Korea,resid others modern_d9,gas,2030,gas,1.0
5093,None Specified,Other-EA,South Korea,resid cooling modern_d1,gas,2030,gas,1.0
5161,None Specified,Other-EA,South Korea,resid cooling modern_d10,gas,2030,gas,1.0
5229,None Specified,Other-EA,South Korea,resid cooling modern_d2,gas,2030,gas,1.0
5297,None Specified,Other-EA,South Korea,resid cooling modern_d3,gas,2030,gas,1.0
5365,None Specified,Other-EA,South Korea,resid cooling modern_d4,gas,2030,gas,1.0
5433,None Specified,Other-EA,South Korea,resid cooling modern_d5,gas,2030,gas,1.0
5501,None Specified,Other-EA,South Korea,resid cooling modern_d6,gas,2030,gas,1.0
5569,None Specified,Other-EA,South Korea,resid cooling modern_d7,gas,2030,gas,1.0
5637,None Specified,Other-EA,South Korea,resid cooling modern_d8,gas,2030,gas,1.0
5705,None Specified,Other-EA,South Korea,resid cooling modern_d9,gas,2030,gas,1.0
6223,None Specified,Other-EA,South Korea,resid heating modern_d1,gas,2030,gas,0.5
6358,None Specified,Other-EA,South Korea,resid heating modern_d10,gas,2030,gas,0.5
6495,None Specified,Other-EA,South Korea,resid heating modern_d2,gas,2030,gas,0.5
6630,None Specified,Other-EA,South Korea,resid heating modern_d3,gas,2030,gas,0.5
6767,None Specified,Other-EA,South Korea,resid heating modern_d4,gas,2030,gas,0.5
6904,None Specified,Other-EA,South Korea,resid heating modern_d5,gas,2030,gas,0.5
7041,None Specified,Other-EA,South Korea,resid heating modern_d6,gas,2030,gas,0.5
7178,None Specified,Other-EA,South Korea,resid heating modern_d7,gas,2030,gas,0.5
7315,None Specified,Other-EA,South Korea,resid heating modern_d8,gas,2030,gas,0.5
7452,None Specified,Other-EA,South Korea,resid heating modern_d9,gas,2030,gas,0.5
8019,None Specified,Other-EA,South Korea,resid others modern_d1,gas,2030,gas,0.5
8156,None Specified,Other-EA,South Korea,resid others modern_d10,gas,2030,gas,0.5
8293,None Specified,Other-EA,South Korea,resid others modern_d2,gas,2030,gas,0.5
8430,None Specified,Other-EA,South Korea,resid others modern_d3,gas,2030,gas,0.5
8567,None Specified,Other-EA,South Korea,resid others modern_d4,gas,2030,gas,0.5
8704,None Specified,Other-EA,South Korea,resid others modern_d5,gas,2030,gas,0.5
8841,None Specified,Other-EA,South Korea,resid others modern_d6,gas,2030,gas,0.5
8978,None Specified,Other-EA,South Korea,resid others modern_d7,gas,2030,gas,0.5
9115,None Specified,Other-EA,South Korea,resid others modern_d8,gas,2030,gas,0.5
9252,None Specified,Other-EA,South Korea,resid others modern_d9,gas,2030,gas,0.5

In [68]:
df = run_query(conn=conn, q_idx=122, scenarios=['Other-CP','Other-EA'], regions=['South Korea'])
df[(df['Year'] >= 2025) & (df['Year'] <= 2030)]

iron and steel prices

       Units  scenario       region          sector  Year     value
6   1975$/kg  Other-CP  South Korea  iron and steel  2025  0.165651
7   1975$/kg  Other-CP  South Korea  iron and steel  2030  0.164223
28  1975$/kg  Other-EA  South Korea  iron and steel  2025  0.165653
29  1975$/kg  Other-EA  South Korea  iron and steel  2030  0.185811

In [69]:
0.156661 * 0.13 * 0.5

0.010182965

In [7]:
dfCO2 = run_query(conn=conn, q_idx=262, scenarios=['Other-CP','Other-EA'], regions=['South Korea'])
dfCO2['GHG'] = 'CO2'
dfNonCO2 = run_query(conn=conn, q_idx=270, scenarios=['Other-CP','Other-EA'], regions=['South Korea'])
df = pd.concat([dfCO2, dfNonCO2])
df["emiss(MT)"] = df.apply(convert_to_mt, axis=1)  # uses your utils.convert_to_mt
df["gwpAr5"]    = df["GHG"].map(GWP_AR5).astype(float)
df["MTCO2eq"]   = df["emiss(MT)"] * df["gwpAr5"]
df[(~df['sector'].isin(['trn_aviation_intl', 'trn_shipping_intl']))].groupby(['scenario', 'Year'])['MTCO2eq'].sum()

CO2 emissions by sector (no bio) (excluding resource production)
nonCO2 emissions by sector (excluding resource production)

scenario  Year
Other-CP  1975     54.590644
          1990    295.171616
          2005    588.834536
          2010    694.980605
          2015    750.755896
          2020    702.605474
          2025    689.204194
          2030    636.915075
          2035    558.711188
Other-EA  1975     54.590644
          1990    295.171616
          2005    588.834536
          2010    694.980605
          2015    750.755896
          2020    718.322268
          2025    692.298845
          2030    531.951948
          2035    360.789351
Name: MTCO2eq, dtype: float64

In [10]:
dfCO2 = run_query(conn=conn, q_idx=265, scenarios=['Other-CP','Other-EA'], regions=['South Korea'])
dfCO2['GHG'] = 'CO2'

CO2 emissions by tech (excluding resource production)

In [11]:
dfCO2[(dfCO2['Year'] >= 2035) & (dfCO2['sector'].str.contains('resid'))]

,Units,scenario,region,sector,subsector,technology,Year,value,GHG
764,MTC,Other-CP,South Korea,resid heating coal_d1,coal,coal,2035,0.038586,CO2
776,MTC,Other-CP,South Korea,resid heating coal_d2,coal,coal,2035,0.029975,CO2
784,MTC,Other-CP,South Korea,resid heating coal_d3,coal,coal,2035,0.026305,CO2
792,MTC,Other-CP,South Korea,resid heating coal_d4,coal,coal,2035,0.013154,CO2
831,MTC,Other-CP,South Korea,resid heating modern_d1,gas,gas,2035,0.228668,CO2
...,...,...,...,...,...,...,...,...,...
2505,MTC,Other-EA,South Korea,resid others modern_d5,gas,gas,2035,0.208632,CO2
2520,MTC,Other-EA,South Korea,resid others modern_d6,gas,gas,2035,0.219550,CO2
2535,MTC,Other-EA,South Korea,resid others modern_d7,gas,gas,2035,0.231642,CO2
2550,MTC,Other-EA,South Korea,resid others modern_d8,gas,gas,2035,0.246399,CO2
2565,MTC,Other-EA,South Korea,resid others modern_d9,gas,gas,2035,0.269132,CO2

In [9]:
558.711188 - 38.3

520.411188

In [10]:
1 - 520.411188 / 742.3

0.29892066819345264

In [32]:
dfCO2Map   = pd.read_csv("./extdata/gcamreport/CO2_tech_map.csv", skiprows=[0])
dfNonCO2Map= pd.read_csv("./extdata/gcamreport/nonCO2_emissions_sector_map.csv", skiprows=[0])

In [32]:
df = run_query(conn=conn, q_idx=265, scenarios=['Other-CP','Other-EA'], regions=['South Korea'])
df['sector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

CO2 emissions by tech (excluding resource production)

array(['H2 central production', 'H2 wholesale dispensing',
       'agricultural energy use', 'airCO2', 'ammonia',
       'backup_electricity', 'cement', 'chemical energy use',
       'chemical feedstocks', 'comm cooling', 'comm heating',
       'comm others', 'construction energy use', 'desalinated water',
       'elec_biomass (IGCC)', 'elec_biomass (conv)',
       'elec_coal (IGCC CCS)', 'elec_coal (conv pul CCS)',
       'elec_coal (conv pul)', 'elec_gas (CC CCS)', 'elec_gas (CC)',
       'elec_gas (steam/CT)', 'elec_refined liquids (CC)',
       'elec_refined liquids (steam/CT)', 'electricity', 'gas processing',
       'iron and steel', 'mining energy use',
       'other industrial energy use', 'process heat cement',
       'process heat dac', 'process heat food processing',
       'process heat paper', 'refining', 'regional biomass',
       'regional biomassOil', 'regional corn for ethanol',
       'regional woodpulp for energy', 'resid heating coal_d1',
       'resid heating coal_d10', 'resid heating coal_d2',
       'resid heating coal_d3', 'resid heating coal_d4',
       'resid heating coal_d5', 'resid heating coal_d6',
       'resid heating coal_d7', 'resid heating coal_d8',
       'resid heating coal_d9', 'resid heating modern_d1',
       'resid heating modern_d10', 'resid heating modern_d2',
       'resid heating modern_d3', 'resid heating modern_d4',
       'resid heating modern_d5', 'resid heating modern_d6',
       'resid heating modern_d7', 'resid heating modern_d8',
       'resid heating modern_d9', 'resid others coal_d1',
       'resid others coal_d10', 'resid others coal_d2',
       'resid others coal_d3', 'resid others coal_d4',
       'resid others coal_d5', 'resid others coal_d6',
       'resid others coal_d7', 'resid others coal_d8',
       'resid others coal_d9', 'resid others modern_d1',
       'resid others modern_d10', 'resid others modern_d2',
       'resid others modern_d3', 'resid others modern_d4',
       'resid others modern_d5', 'resid others modern_d6',
       'resid others modern_d7', 'resid others modern_d8',
       'resid others modern_d9', 'trn_aviation_intl', 'trn_freight',
       'trn_freight_road', 'trn_pass', 'trn_pass_road',
       'trn_pass_road_LDV', 'trn_pass_road_LDV_4W', 'trn_shipping_intl',
       'waste biomass for paper'], dtype=object)

In [8]:
df = run_query(conn=conn, q_idx=273, scenarios=['Power-CP'], regions=['South Korea'])
df['sector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

nonCO2 emissions by tech (excluding resource production)

array(['comm cooling', 'electricity_net_ownuse', 'industrial processes',
       'resid cooling modern_d1', 'resid cooling modern_d10',
       'resid cooling modern_d2', 'resid cooling modern_d3',
       'resid cooling modern_d4', 'resid cooling modern_d5',
       'resid cooling modern_d6', 'resid cooling modern_d7',
       'resid cooling modern_d8', 'resid cooling modern_d9',
       'urban processes', 'Beef', 'Corn', 'Dairy', 'FiberCrop',
       'FodderGrass', 'Fruits', 'H2 central production',
       'H2 liquid truck', 'H2 pipeline', 'H2 wholesale dispensing',
       'Legumes', 'MiscCrop', 'NutsSeeds', 'OilCrop', 'OtherGrain',
       'Pork', 'Poultry', 'Rice', 'RootTuber', 'SheepGoat', 'Soybean',
       'UnmanagedLand', 'Vegetables', 'Wheat', 'agricultural energy use',
       'ammonia', 'backup_electricity', 'biomass', 'chemical energy use',
       'comm heating', 'comm others', 'construction energy use',
       'electricity', 'iron and steel', 'mining energy use',
       'other industrial energy use', 'process heat cement',
       'process heat food processing', 'process heat paper', 'refining',
       'resid heating TradBio_d1', 'resid heating TradBio_d10',
       'resid heating TradBio_d2', 'resid heating TradBio_d3',
       'resid heating TradBio_d4', 'resid heating TradBio_d5',
       'resid heating TradBio_d6', 'resid heating TradBio_d7',
       'resid heating TradBio_d8', 'resid heating TradBio_d9',
       'resid heating coal_d1', 'resid heating coal_d10',
       'resid heating coal_d2', 'resid heating coal_d3',
       'resid heating coal_d4', 'resid heating coal_d5',
       'resid heating coal_d6', 'resid heating coal_d7',
       'resid heating coal_d8', 'resid heating coal_d9',
       'resid heating modern_d1', 'resid heating modern_d10',
       'resid heating modern_d2', 'resid heating modern_d3',
       'resid heating modern_d4', 'resid heating modern_d5',
       'resid heating modern_d6', 'resid heating modern_d7',
       'resid heating modern_d8', 'resid heating modern_d9',
       'resid others TradBio_d1', 'resid others TradBio_d10',
       'resid others TradBio_d2', 'resid others TradBio_d3',
       'resid others TradBio_d4', 'resid others TradBio_d5',
       'resid others TradBio_d6', 'resid others TradBio_d7',
       'resid others TradBio_d8', 'resid others TradBio_d9',
       'resid others coal_d1', 'resid others coal_d10',
       'resid others coal_d2', 'resid others coal_d3',
       'resid others coal_d4', 'resid others coal_d5',
       'resid others coal_d6', 'resid others coal_d7',
       'resid others coal_d8', 'resid others coal_d9',
       'resid others modern_d1', 'resid others modern_d10',
       'resid others modern_d2', 'resid others modern_d3',
       'resid others modern_d4', 'resid others modern_d5',
       'resid others modern_d6', 'resid others modern_d7',
       'resid others modern_d8', 'resid others modern_d9',
       'trn_aviation_intl', 'trn_freight', 'trn_freight_road', 'trn_pass',
       'trn_pass_road', 'trn_pass_road_LDV', 'trn_pass_road_LDV_4W',
       'trn_shipping_intl', 'waste biomass for paper'], dtype=object)

In [9]:
listCrop = [
    'Corn', 'FiberCrop', 'FodderGrass', 'Fruits', 'Legumes', 'MiscCrop', 'NutsSeeds', 
    'OilCrop', 'OtherGrain', 'RootTuber', 'Soybean', 'Vegetables', 'Wheat',
]

In [10]:
df[(df['sector'].isin(listCrop))]['technology'].unique()

array(['CornC4_Korea_RFD_hi', 'CornC4_Korea_RFD_lo',
       'FiberCrop_Korea_IRR_hi', 'FiberCrop_Korea_IRR_lo',
       'FiberCrop_Korea_RFD_hi', 'FiberCrop_Korea_RFD_lo',
       'FodderGrass_Korea_RFD_hi', 'FodderGrass_Korea_RFD_lo',
       'FruitsTree_Korea_IRR_hi', 'FruitsTree_Korea_IRR_lo',
       'FruitsTree_Korea_RFD_hi', 'FruitsTree_Korea_RFD_lo',
       'Fruits_Korea_IRR_hi', 'Fruits_Korea_IRR_lo',
       'Fruits_Korea_RFD_hi', 'Fruits_Korea_RFD_lo',
       'Legumes_Korea_RFD_hi', 'Legumes_Korea_RFD_lo',
       'MiscCrop_Korea_IRR_hi', 'MiscCrop_Korea_IRR_lo',
       'MiscCrop_Korea_RFD_hi', 'MiscCrop_Korea_RFD_lo',
       'NutsSeedsTree_Korea_IRR_hi', 'NutsSeedsTree_Korea_IRR_lo',
       'NutsSeedsTree_Korea_RFD_hi', 'NutsSeedsTree_Korea_RFD_lo',
       'NutsSeeds_Korea_RFD_hi', 'NutsSeeds_Korea_RFD_lo',
       'OilCrop_Korea_IRR_hi', 'OilCrop_Korea_IRR_lo',
       'OilCrop_Korea_RFD_hi', 'OilCrop_Korea_RFD_lo',
       'OtherGrainC4_Korea_RFD_hi', 'OtherGrainC4_Korea_RFD_lo',
       'OtherGrain_Korea_IRR_hi', 'OtherGrain_Korea_IRR_lo',
       'OtherGrain_Korea_RFD_hi', 'OtherGrain_Korea_RFD_lo',
       'RootTuber_Korea_IRR_hi', 'RootTuber_Korea_IRR_lo',
       'RootTuber_Korea_RFD_hi', 'RootTuber_Korea_RFD_lo',
       'Soybean_Korea_IRR_hi', 'Soybean_Korea_IRR_lo',
       'Soybean_Korea_RFD_hi', 'Soybean_Korea_RFD_lo',
       'Vegetables_Korea_IRR_hi', 'Vegetables_Korea_IRR_lo',
       'Vegetables_Korea_RFD_hi', 'Vegetables_Korea_RFD_lo',
       'Wheat_Korea_RFD_hi', 'Wheat_Korea_RFD_lo'], dtype=object)

In [11]:
df["emiss(MT)"] = df.apply(convert_to_mt, axis=1)  # uses your utils.convert_to_mt
df["gwpAr5"]    = df["GHG"].map(GWP_AR5).astype(float)
df["MTCO2eq"]   = df["emiss(MT)"] * df["gwpAr5"]
df[(df['sector'].isin(listCrop))].groupby(['Year', 'scenario'])['MTCO2eq'].sum()

Year  scenario
1975  Power-CP    1.956932
1990  Power-CP    2.296362
2005  Power-CP    2.277849
2010  Power-CP    1.803642
2015  Power-CP    2.001942
2020  Power-CP    2.081022
2025  Power-CP    2.119450
2030  Power-CP    2.152947
2035  Power-CP    2.178591
Name: MTCO2eq, dtype: float64

In [17]:
df[(df['GHG'].str.contains('HFC'))].groupby(['Year', 'scenario'])['MTCO2eq'].sum()

Year  scenario
1990  Power-CP     0.040795
2005  Power-CP    15.341120
2010  Power-CP    23.340671
2015  Power-CP    25.690444
2020  Power-CP    28.499158
2025  Power-CP    30.077220
2030  Power-CP    30.820361
2035  Power-CP    30.305728
Name: MTCO2eq, dtype: float64

In [ ]:
df = run_query(conn=conn, q_idx=166, scenarios=['Power-CP'], regions=['South Korea'])
df['subsector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

In [ ]:
df = run_query(conn=conn, q_idx=166, scenarios=['Power-CP'], regions=['South Korea'])
df['subsector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

In [17]:
df = run_query(conn=conn, q_idx=166, scenarios=['Power-CP'], regions=['South Korea'])
df['subsector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

costs of transport techs

array(['International Aviation', 'Domestic Aviation', 'HSR',
       'Passenger Rail', 'road', 'Bus', 'LDV', '2W and 3W', '4W', 'Car',
       'Large Car and Truck', 'Domestic Ship', 'Freight Rail',
       'Medium truck', 'International Ship'], dtype=object)

In [18]:
dfPol = df[((df['subsector'] == 'Domestic Ship')) & (df['Year'] >= 2025) & (df['Year'] <= 2035)].copy()
# dfPol['subsidy_cp'] = dfPol['value'] * (-0.2)
# dfPol['subsidy_cp'] = dfPol['value'] * (-0.2)
dfPol

,Units,scenario,region,sector,subsector,technology,Year,value
267,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,BEV,2025,0.015547
268,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,BEV,2030,0.011832
269,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,BEV,2035,0.008128
276,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,FCEV,2025,0.010209
277,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,FCEV,2030,0.009685
278,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,FCEV,2035,0.009247
285,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Hybrid Liquids,2025,0.005660
286,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Hybrid Liquids,2030,0.005644
287,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Hybrid Liquids,2035,0.005389
294,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Liquids,2025,0.006466
295,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Liquids,2030,0.006541
296,1990$/ton-km,Power-CP,South Korea,trn_freight,Domestic Ship,Liquids,2035,0.006420

In [7]:
df = run_query(conn=conn, q_idx=170, scenarios=['Power-CP'], regions=['South Korea'])
df['sector'].unique()#[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

transport tech share-weights

array(['trn_aviation_intl', 'trn_freight', 'trn_freight_road', 'trn_pass',
       'trn_pass_road', 'trn_pass_road_LDV', 'trn_pass_road_LDV_4W',
       'trn_shipping_intl'], dtype=object)

In [11]:
df[(df['subsector'] == 'Medium truck') & (df['Year'] >= 2020) & (df['Year'] <= 2035)]

,Units,scenario,region,sector,subsector,Year,technology,value
237,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2020,Hybrid Liquids,0.158869
238,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2020,Liquids,1.000000
239,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,BEV,0.034445
240,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,FCEV,0.034445
241,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,Hybrid Liquids,0.841131
242,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,Liquids,1.000000
243,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,BEV,0.158869
244,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,FCEV,0.158869
245,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,Hybrid Liquids,1.000000
246,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,Liquids,1.000000
247,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,BEV,0.500000
248,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,FCEV,0.500000
249,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,Hybrid Liquids,1.000000
250,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,Liquids,1.000000

In [10]:
df[(df['sector'] == 'trn_freight_road') & (df['Year'] >= 2020) & (df['Year'] <= 2035)]

,Units,scenario,region,sector,subsector,Year,technology,value
237,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2020,Hybrid Liquids,0.158869
238,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2020,Liquids,1.000000
239,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,BEV,0.034445
240,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,FCEV,0.034445
241,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,Hybrid Liquids,0.841131
242,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2025,Liquids,1.000000
243,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,BEV,0.158869
244,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,FCEV,0.158869
245,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,Hybrid Liquids,1.000000
246,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2030,Liquids,1.000000
247,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,BEV,0.500000
248,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,FCEV,0.500000
249,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,Hybrid Liquids,1.000000
250,None Specified,Power-CP,South Korea,trn_freight_road,Medium truck,2035,Liquids,1.000000

In [9]:
df[(df['sector'] == 'trn_pass_road_LDV_4W') & (df['Year'] >= 2020) & (df['Year'] <= 2035)]

,Units,scenario,region,sector,subsector,Year,technology,value
666,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2020,Hybrid Liquids,0.158869
667,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2020,Liquids,1.000000
668,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2020,NG,0.001004
669,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2025,BEV,0.500000
670,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2025,FCEV,0.500000
671,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2025,Hybrid Liquids,0.841131
672,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2025,Liquids,1.000000
673,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2025,NG,0.001004
674,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2030,BEV,1.000000
675,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2030,FCEV,1.000000
676,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2030,Hybrid Liquids,1.000000
677,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2030,Liquids,1.000000
678,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2030,NG,0.001004
679,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2035,BEV,1.000000
680,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2035,FCEV,1.000000
681,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2035,Hybrid Liquids,1.000000
682,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2035,Liquids,1.000000
683,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Car,2035,NG,0.001004
757,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2020,Hybrid Liquids,0.158869
758,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2020,Liquids,1.000000
759,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2020,NG,0.001143
760,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2025,BEV,0.500000
761,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2025,FCEV,0.500000
762,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2025,Hybrid Liquids,0.841131
763,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2025,Liquids,1.000000
764,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2025,NG,0.001143
765,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2030,BEV,1.000000
766,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2030,FCEV,1.000000
767,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2030,Hybrid Liquids,1.000000
768,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2030,Liquids,1.000000
769,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2030,NG,0.001143
770,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,BEV,1.000000
771,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,FCEV,1.000000
772,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,Hybrid Liquids,1.000000
773,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,Liquids,1.000000
774,None Specified,Power-CP,South Korea,trn_pass_road_LDV_4W,Large Car and Truck,2035,NG,0.001143

In [24]:
df = run_query(conn=conn, q_idx=100, scenarios=['Power-CP'], regions=['South Korea'])
df[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

industry final energy by tech and fuel

,Units,scenario,region,sector,subsector,technology,input,Year,value
83,EJ,Power-CP,South Korea,chemical energy use,biomass,biomass,delivered biomass,2030,0.011847
87,EJ,Power-CP,South Korea,chemical energy use,biomass,biomass CCS,delivered biomass,2030,0.000059
95,EJ,Power-CP,South Korea,chemical energy use,coal,coal,delivered coal,2030,0.004963
99,EJ,Power-CP,South Korea,chemical energy use,coal,coal CCS,delivered coal,2030,0.000010
108,EJ,Power-CP,South Korea,chemical energy use,electricity,electricity,elect_td_ind,2030,0.189090
114,EJ,Power-CP,South Korea,chemical energy use,gas,gas,wholesale gas,2030,0.048086
118,EJ,Power-CP,South Korea,chemical energy use,gas,gas CCS,wholesale gas,2030,0.000561
126,EJ,Power-CP,South Korea,chemical energy use,refined liquids,refined liquids,refined liquids industrial,2030,0.022880
130,EJ,Power-CP,South Korea,chemical energy use,refined liquids,refined liquids CCS,refined liquids industrial,2030,0.000352
136,EJ,Power-CP,South Korea,chemical feedstocks,coal,coal,delivered coal,2030,0.024484
145,EJ,Power-CP,South Korea,chemical feedstocks,refined liquids,refined liquids,refined liquids industrial,2030,1.873190

In [23]:
df = run_query(conn=conn, q_idx=268, scenarios=['Power-CP'], regions=['South Korea'])
df[(df['Year'] == 2030) & (df['sector'].str.contains('chemical'))]#['value'].sum()

CO2 sequestration by tech

,Units,scenario,region,sector,subsector,technology,Year,value
16,MTC,Power-CP,South Korea,chemical energy use,biomass,biomass CCS,2030,0.001231
20,MTC,Power-CP,South Korea,chemical energy use,coal,coal CCS,2030,0.000237
24,MTC,Power-CP,South Korea,chemical energy use,gas,gas CCS,2030,0.007169
28,MTC,Power-CP,South Korea,chemical energy use,refined liquids,refined liquids CCS,2030,0.006206
37,MTC,Power-CP,South Korea,chemical feedstocks,refined liquids,refined liquids,2030,36.714500

In [13]:
df = run_query(conn=conn, q_idx=321, scenarios=['Power-CP'], regions=['South Korea'])
df#[(df['Year'] == 2020) & (df['subsector'] == 'gas')]#['value'].sum()

costs by tech

,Units,scenario,region,sector,subsector,Year,technology,value
0,$/GJ,Power-CP,South Korea,woodpulp_energy,woodpulp_energy,1975,woodpulp_energy,6.923830
1,$/GJ,Power-CP,South Korea,woodpulp_energy,woodpulp_energy,1990,woodpulp_energy,98.457800
2,$/GJ,Power-CP,South Korea,woodpulp_energy,woodpulp_energy,2005,woodpulp_energy,51.642100
3,$/GJ,Power-CP,South Korea,woodpulp_energy,woodpulp_energy,2010,woodpulp_energy,45.543000
4,$/GJ,Power-CP,South Korea,woodpulp_energy,woodpulp_energy,2015,woodpulp_energy,26.855700
...,...,...,...,...,...,...,...,...
6175,1990$/ton-km,Power-CP,South Korea,trn_shipping_intl,International Ship,2030,Liquids,0.002578
6176,1990$/ton-km,Power-CP,South Korea,trn_shipping_intl,International Ship,2035,BEV,0.004874
6177,1990$/ton-km,Power-CP,South Korea,trn_shipping_intl,International Ship,2035,FCEV,0.004116
6178,1990$/ton-km,Power-CP,South Korea,trn_shipping_intl,International Ship,2035,Hybrid Liquids,0.002262
6179,1990$/ton-km,Power-CP,South Korea,trn_shipping_intl,International Ship,2035,Liquids,0.002541

In [14]:
df[(df['sector'] == 'carbon-storage')]

,Units,scenario,region,sector,subsector,Year,technology,value
5982,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,1975,offshore carbon-storage,212.00
5983,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,1990,offshore carbon-storage,212.00
5984,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2005,offshore carbon-storage,212.00
5985,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2010,offshore carbon-storage,212.00
5986,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2015,offshore carbon-storage,212.00
5987,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2020,offshore carbon-storage,212.00
5988,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2025,offshore carbon-storage,212.00
5989,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2030,offshore carbon-storage,212.00
5990,1990$/tC,Power-CP,South Korea,carbon-storage,offshore carbon-storage,2035,offshore carbon-storage,212.00
5991,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,1975,onshore carbon-storage,1.00
5992,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,1990,onshore carbon-storage,1.00
5993,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2005,onshore carbon-storage,1.00
5994,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2010,onshore carbon-storage,1.00
5995,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2015,onshore carbon-storage,1.00
5996,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2020,onshore carbon-storage,8938.28
5997,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2025,onshore carbon-storage,19663.00
5998,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2030,onshore carbon-storage,30745.30
5999,1990$/tC,Power-CP,South Korea,carbon-storage,onshore carbon-storage,2035,onshore carbon-storage,41899.00

In [25]:
df = run_query(conn=conn, q_idx=11, scenarios=['Power-CP'], regions=['South Korea'])
df[(df['Year'] == 2020) & (df['subsector'] == 'gas')]#['value'].sum()

elec gen by gen tech and cooling tech and vintage

,Units,scenario,region,sector,subsector,technology,output,Year,value
224,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (dry cooling),year=2015",elec_gas (CC),2020,0.012519
228,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (dry cooling),year=2020",elec_gas (CC),2020,0.001774
242,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (once through),year=2015",elec_gas (CC),2020,0.002087
250,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (recirculating),year=2015",elec_gas (CC),2020,0.270339
254,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (recirculating),year=2020",elec_gas (CC),2020,0.067489
268,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (seawater),year=2015",elec_gas (CC),2020,0.068611
272,EJ,Power-CP,South Korea,electricity,gas,"gas (CC) (seawater),year=2020",elec_gas (CC),2020,0.018227
286,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (dry cooling),year=2015",elec_gas (steam/CT),2020,0.000078
290,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (dry cooling),year=2020",elec_gas (steam/CT),2020,0.000016
304,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (once through),year=2015",elec_gas (steam/CT),2020,0.000010
312,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (recirculating),year=2015",elec_gas (steam/CT),2020,0.001677
316,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (recirculating),year=2020",elec_gas (steam/CT),2020,0.000545
330,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (seawater),year=2015",elec_gas (steam/CT),2020,0.000428
334,EJ,Power-CP,South Korea,electricity,gas,"gas (steam/CT) (seawater),year=2020",elec_gas (steam/CT),2020,0.000147

In [17]:
5260 / 4333

1.2139395338102932

In [18]:
5920 / 4333

1.3662589429956151

In [20]:
5530 / 4333

1.2762520193861067

In [22]:
3090 / 4333

0.7131317793676437